/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  SnowflakePlugin: () => SnowflakePlugin,
  default: () => SnowflakePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian9 = require("obsidian");

// src/ui/settings-tab.ts
var import_obsidian = require("obsidian");

// src/pattern-matcher.ts
function matchesExclusionPattern(filePath, patterns) {
  var _a;
  if (!patterns || patterns.length === 0) {
    return false;
  }
  const fileName = (_a = filePath.split("/").pop()) != null ? _a : filePath;
  return patterns.some((pattern) => {
    if (!pattern || pattern.trim() === "") {
      return false;
    }
    if (pattern.endsWith("/")) {
      const dirPath = pattern.slice(0, -1);
      return filePath.startsWith(dirPath + "/") || filePath === dirPath;
    }
    if (pattern === filePath || pattern === fileName) {
      return true;
    }
    const regexPattern = globToRegex(pattern);
    return regexPattern.test(filePath) || regexPattern.test(fileName);
  });
}
function globToRegex(glob) {
  let pattern = glob.replace(/[.+^${}()|[\]\\]/g, "\\$&");
  pattern = pattern.replace(/\*\*/g, "{{DOUBLESTAR}}").replace(/\*/g, "[^/]*").replace(/\?/g, ".").replace(/{{DOUBLESTAR}}/g, ".*");
  pattern = "^" + pattern + "$";
  return new RegExp(pattern);
}
function normalizePattern(pattern) {
  pattern = pattern.trim();
  if (pattern.startsWith("/")) {
    pattern = pattern.slice(1);
  }
  return pattern;
}
function processExclusionPatterns(input) {
  if (!input || input.trim() === "") {
    return {
      patterns: [],
      isValid: true,
      errors: []
    };
  }
  const rawPatterns = input.split("\n");
  const normalizedPatterns = [];
  const errors = [];
  rawPatterns.forEach((pattern, index) => {
    const normalized = normalizePattern(pattern);
    if (normalized === "") {
      return;
    }
    if (pattern.includes("\0")) {
      errors.push(`Line ${String(index + 1)}: Pattern contains invalid null character`);
      return;
    }
    normalizedPatterns.push(normalized);
  });
  return {
    patterns: normalizedPatterns,
    isValid: errors.length === 0,
    errors
  };
}

// src/ui/settings-tab.ts
var SnowflakeSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    this.addHeader(containerEl);
    this.addGlobalExcludeSettings(containerEl);
    this.addVariableFormatSettings(containerEl);
    this.addHelpSection(containerEl);
  }
  addHeader(containerEl) {
    containerEl.createEl("h1", { text: "Snowflake Settings" });
    containerEl.createEl("p", {
      text: "Snowflake applies templates to new notes from a SCHEMA.md file in their folder (and any ancestor folders, root \u2192 leaf). Add a SCHEMA.md to any folder to make it Snowflake-managed.",
      cls: "setting-item-description"
    });
  }
  addGlobalExcludeSettings(containerEl) {
    containerEl.createEl("h2", { text: "Global Exclude Patterns" });
    containerEl.createEl("p", {
      text: "Files matching these patterns are skipped by Snowflake. One pattern per line.",
      cls: "setting-item-description"
    });
    const patterns = this.plugin.settings.globalExcludePatterns;
    const currentValue = patterns.length > 0 ? patterns.join("\n") : "";
    new import_obsidian.Setting(containerEl).setName("Exclude patterns").setDesc(
      "Glob patterns: * matches characters, ** matches directories, ? matches single character"
    ).addTextArea((text) => {
      text.setPlaceholder("*.tmp\n_archive/**\n~*.md").setValue(currentValue).onChange(async (value) => {
        const result = processExclusionPatterns(value);
        this.plugin.settings.globalExcludePatterns = result.patterns;
        await this.plugin.saveSettings();
      });
      text.inputEl.rows = 4;
      text.inputEl.cols = 30;
      return text;
    });
  }
  addVariableFormatSettings(containerEl) {
    containerEl.createEl("h2", { text: "Variable Formats" });
    containerEl.createEl("p", {
      text: "Customize the format for date and time variables in templates",
      cls: "setting-item-description"
    });
    new import_obsidian.Setting(containerEl).setName("Date format").setDesc("Format for {{date}} variable (uses moment.js format)").addText((text) => {
      var _a;
      text.setPlaceholder("YYYY-MM-DD").setValue(this.plugin.settings.dateFormat);
      const preview = (_a = text.inputEl.parentElement) == null ? void 0 : _a.createDiv({
        cls: "setting-item-description",
        text: `Preview: ${window.moment().format(this.plugin.settings.dateFormat)}`
      });
      text.onChange(async (value) => {
        const format = value || "YYYY-MM-DD";
        this.plugin.settings.dateFormat = format;
        await this.plugin.saveSettings();
        if (preview) {
          try {
            preview.textContent = `Preview: ${window.moment().format(format)}`;
          } catch (e) {
            preview.textContent = "Preview: Invalid format";
          }
        }
      });
      return text;
    });
    new import_obsidian.Setting(containerEl).setName("Time format").setDesc("Format for {{time}} variable (uses moment.js format)").addText((text) => {
      var _a;
      text.setPlaceholder("HH:mm").setValue(this.plugin.settings.timeFormat);
      const preview = (_a = text.inputEl.parentElement) == null ? void 0 : _a.createDiv({
        cls: "setting-item-description",
        text: `Preview: ${window.moment().format(this.plugin.settings.timeFormat)}`
      });
      text.onChange(async (value) => {
        const format = value || "HH:mm";
        this.plugin.settings.timeFormat = format;
        await this.plugin.saveSettings();
        if (preview) {
          try {
            preview.textContent = `Preview: ${window.moment().format(format)}`;
          } catch (e) {
            preview.textContent = "Preview: Invalid format";
          }
        }
      });
      return text;
    });
    containerEl.createEl("p", {
      cls: "setting-item-description",
      text: "Common formats: YYYY-MM-DD, DD/MM/YYYY, MMM DD YYYY, HH:mm:ss, h:mm A"
    });
  }
  addHelpSection(containerEl) {
    containerEl.createEl("h2", { text: "Template Variables" });
    containerEl.createEl("p", {
      text: "You can use these variables in your SCHEMA.md templates:",
      cls: "setting-item-description"
    });
    const variableList = containerEl.createEl("ul", {
      cls: "setting-item-description"
    });
    variableList.createEl("li", { text: "{{title}} - The filename without extension" });
    variableList.createEl("li", {
      text: `{{date}} - Current date (using your format: ${this.plugin.settings.dateFormat})`
    });
    variableList.createEl("li", {
      text: `{{time}} - Current time (using your format: ${this.plugin.settings.timeFormat})`
    });
    variableList.createEl("li", { text: "{{snowflake_id}} - Unique 10-character ID" });
  }
};

// src/constants.ts
var DEFAULT_SETTINGS = {
  dateFormat: "YYYY-MM-DD",
  timeFormat: "HH:mm",
  globalExcludePatterns: []
};
var SCHEMA_FILE_NAME = "SCHEMA.md";
var ID_CONFIG = {
  length: 10,
  alphabet: "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
};

// src/settings-utils.ts
function areSettingsValid(settings) {
  if (settings === null || settings === void 0 || typeof settings !== "object") {
    return false;
  }
  const s = settings;
  if (!("dateFormat" in s && typeof s.dateFormat === "string" && "timeFormat" in s && typeof s.timeFormat === "string" && "globalExcludePatterns" in s && Array.isArray(s.globalExcludePatterns) && s.globalExcludePatterns.every((p) => typeof p === "string"))) {
    return false;
  }
  return true;
}
function migrateSettings(settings) {
  if (areSettingsValid(settings)) {
    return cleanSettings(settings);
  }
  if (settings !== null && settings !== void 0 && typeof settings === "object") {
    const s = settings;
    const migrated = { ...DEFAULT_SETTINGS };
    if (typeof s.dateFormat === "string" && s.dateFormat.trim() !== "") {
      migrated.dateFormat = s.dateFormat;
    }
    if (typeof s.timeFormat === "string" && s.timeFormat.trim() !== "") {
      migrated.timeFormat = s.timeFormat;
    }
    if (Array.isArray(s.globalExcludePatterns) && s.globalExcludePatterns.every((p) => typeof p === "string")) {
      migrated.globalExcludePatterns = s.globalExcludePatterns;
    }
    return migrated;
  }
  return { ...DEFAULT_SETTINGS };
}
function cleanSettings(settings) {
  return {
    dateFormat: settings.dateFormat || DEFAULT_SETTINGS.dateFormat,
    timeFormat: settings.timeFormat || DEFAULT_SETTINGS.timeFormat,
    globalExcludePatterns: settings.globalExcludePatterns || DEFAULT_SETTINGS.globalExcludePatterns
  };
}

// src/file-creation-handler.ts
var import_obsidian5 = require("obsidian");

// src/types.ts
function isMarkdownFile(file) {
  return file.extension === "md";
}

// src/template-loader.ts
var import_obsidian3 = require("obsidian");

// src/error-handler.ts
var import_obsidian2 = require("obsidian");
var ErrorHandler = class _ErrorHandler {
  constructor() {
    this.debugMode = false;
  }
  /**
   * Get singleton instance
   */
  static getInstance() {
    var _a;
    (_a = _ErrorHandler.instance) != null ? _a : _ErrorHandler.instance = new _ErrorHandler();
    return _ErrorHandler.instance;
  }
  /**
   * Enable/disable debug mode
   */
  setDebugMode(enabled) {
    this.debugMode = enabled;
  }
  /**
   * Handle an error with appropriate user feedback
   *
   * @param error - The error to handle
   * @param context - Context about where the error occurred
   * @returns User-friendly error message
   */
  handleError(error, context) {
    const errorType = this.categorizeError(error);
    const userMessage = this.getUserMessage(errorType, context, error);
    this.logError(error, context, errorType);
    new import_obsidian2.Notice(userMessage);
    return userMessage;
  }
  /**
   * Handle error without showing notice (for cases where caller handles UI)
   */
  handleErrorSilently(error, context) {
    const errorType = this.categorizeError(error);
    const userMessage = this.getUserMessage(errorType, context, error);
    this.logError(error, context, errorType);
    return userMessage;
  }
  /**
   * Categorize the error type
   */
  categorizeError(error) {
    if (error === null || error === void 0) return "UNKNOWN" /* UNKNOWN */;
    const errorMessage = this.getErrorMessage(error).toLowerCase();
    if (this.isFileNotFoundError(errorMessage)) {
      return "FILE_NOT_FOUND" /* FILE_NOT_FOUND */;
    }
    if (this.isPermissionError(errorMessage)) {
      return "PERMISSION_DENIED" /* PERMISSION_DENIED */;
    }
    if (this.isTemplateSyntaxError(errorMessage)) {
      return "INVALID_TEMPLATE_SYNTAX" /* INVALID_TEMPLATE_SYNTAX */;
    }
    if (this.isVariableError(errorMessage)) {
      return "INVALID_VARIABLE" /* INVALID_VARIABLE */;
    }
    return "UNKNOWN" /* UNKNOWN */;
  }
  getErrorMessage(error) {
    if (error instanceof Error) {
      return error.message;
    }
    return String(error);
  }
  isFileNotFoundError(message) {
    return message.includes("file not found") || message.includes("enoent") || message.includes("no such file");
  }
  isPermissionError(message) {
    return message.includes("permission") || message.includes("eacces") || message.includes("access denied");
  }
  isTemplateSyntaxError(message) {
    return message.includes("invalid template") || message.includes("template syntax");
  }
  isVariableError(message) {
    return message.includes("invalid variable") || message.includes("unknown variable");
  }
  /**
   * Get user-friendly error message based on error type and context
   */
  getUserMessage(errorType, context, error) {
    switch (errorType) {
      case "TEMPLATE_NOT_FOUND" /* TEMPLATE_NOT_FOUND */:
        return this.getTemplateNotFoundMessage(context);
      case "FILE_NOT_FOUND" /* FILE_NOT_FOUND */:
        return this.getFileNotFoundMessage(context);
      case "PERMISSION_DENIED" /* PERMISSION_DENIED */:
        return this.getPermissionDeniedMessage(context);
      case "INVALID_TEMPLATE_SYNTAX" /* INVALID_TEMPLATE_SYNTAX */:
        return this.getInvalidSyntaxMessage(context);
      case "INVALID_VARIABLE" /* INVALID_VARIABLE */:
        return this.getInvalidVariableMessage(context);
      case "MERGE_CONFLICT" /* MERGE_CONFLICT */:
        return "Error merging frontmatter. Using existing content.";
      default:
        return this.getGenericErrorMessage(context, error);
    }
  }
  getTemplateNotFoundMessage(context) {
    var _a;
    const path = (_a = context.templatePath) != null ? _a : "unknown";
    return `Template not found: ${path}. Creating file without template.`;
  }
  getFileNotFoundMessage(context) {
    var _a, _b;
    if (context.operation === "load_template") {
      return `Template file not found: ${(_a = context.templatePath) != null ? _a : "unknown"}`;
    }
    return `File not found: ${(_b = context.filePath) != null ? _b : "unknown"}`;
  }
  getPermissionDeniedMessage(context) {
    var _a, _b, _c;
    if (context.operation === "load_template") {
      const path2 = (_a = context.templatePath) != null ? _a : "unknown";
      return `Cannot read template (permission denied): ${path2}. Creating file without template.`;
    }
    const path = (_c = (_b = context.filePath) != null ? _b : context.templatePath) != null ? _c : "unknown";
    return `Permission denied accessing: ${path}`;
  }
  getInvalidSyntaxMessage(context) {
    var _a;
    const path = (_a = context.templatePath) != null ? _a : "unknown";
    return `Template contains invalid syntax and will be used as-is: ${path}`;
  }
  getInvalidVariableMessage(context) {
    var _a;
    const path = (_a = context.templatePath) != null ? _a : "unknown";
    return `Template contains invalid variables that will be left unchanged: ${path}`;
  }
  getGenericErrorMessage(context, error) {
    const operation = this.getOperationDescription(context.operation);
    const errorMessage = error instanceof Error ? error.message : "Unknown error";
    return `Error ${operation}: ${errorMessage}`;
  }
  /**
   * Get human-readable operation description
   */
  getOperationDescription(operation) {
    switch (operation) {
      case "load_template":
        return "loading template";
      case "apply_template":
        return "applying template";
      case "merge_frontmatter":
        return "merging frontmatter";
      default:
        return "processing";
    }
  }
  /**
   * Log error for debugging
   */
  logError(error, context, errorType) {
    const logMessage = {
      timestamp: (/* @__PURE__ */ new Date()).toISOString(),
      errorType,
      context,
      error: error instanceof Error ? {
        message: error.message,
        stack: error.stack,
        name: error.name
      } : String(error)
    };
    console.error("[Snowflake Plugin Error]", logMessage);
    if (this.debugMode) {
      console.error("[Snowflake Debug] Full error details:", error);
    }
  }
  /**
   * Create an ExtendedError with context
   */
  createError(message, type, context, originalError) {
    const error = new Error(message);
    error.type = type;
    error.context = context;
    error.originalError = originalError;
    return error;
  }
  /**
   * Check if an error is a specific type
   */
  isErrorType(error, type) {
    if (error !== null && error !== void 0 && typeof error === "object" && "type" in error) {
      return error.type === type;
    }
    return false;
  }
};

// src/template-loader.ts
var TemplateLoader = class {
  constructor(vault, settings) {
    this.vault = vault;
    this.settings = settings;
    this.errorHandler = ErrorHandler.getInstance();
  }
  async loadTemplate(templatePath) {
    try {
      const templateFile = this.vault.getAbstractFileByPath(templatePath);
      if (!templateFile || !(templateFile instanceof import_obsidian3.TFile)) {
        console.warn(`Template not found: ${templatePath}`);
        return null;
      }
      const content = await this.vault.read(templateFile);
      return content;
    } catch (error) {
      const errorContext = {
        operation: "load_template",
        templatePath
      };
      this.errorHandler.handleErrorSilently(error, errorContext);
      return null;
    }
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  /**
   * Build the SCHEMA.md inheritance chain for a file.
   *
   * Walks from vault root down to the file's parent folder; every folder that
   * contains a SCHEMA.md contributes one entry to the chain (root first).
   * If the file matches a global exclude pattern, returns an empty chain.
   */
  getTemplateChain(file) {
    if (this.isFileExcluded(file)) {
      return { templates: [], hasInheritance: false };
    }
    const templates = [];
    const folderPaths = this.getFolderHierarchy(file);
    for (let i = 0; i < folderPaths.length; i++) {
      const folderPath = folderPaths[i];
      const schemaPath = this.schemaPathFor(folderPath);
      const schemaFile = this.vault.getAbstractFileByPath(schemaPath);
      if (schemaFile instanceof import_obsidian3.TFile) {
        templates.push({
          path: schemaPath,
          folderPath,
          depth: i
        });
      }
    }
    return {
      templates,
      hasInheritance: templates.length > 1
    };
  }
  async loadTemplateChain(chain) {
    const loadedTemplates = [];
    for (const template of chain.templates) {
      const content = await this.loadTemplate(template.path);
      if (content !== null) {
        loadedTemplates.push({ ...template, content });
      } else {
        console.warn(`Skipping missing template in chain: ${template.path}`);
      }
    }
    return {
      templates: loadedTemplates,
      hasInheritance: loadedTemplates.length > 1
    };
  }
  /**
   * Folder paths from vault root to the file's immediate parent.
   * Root is represented as the empty string.
   */
  getFolderHierarchy(file) {
    var _a;
    const paths = [""];
    const folderPath = (_a = file.parent) == null ? void 0 : _a.path;
    if (folderPath === void 0 || folderPath === "" || folderPath === "/") {
      return paths;
    }
    const parts = folderPath.split("/").filter((p) => p !== "");
    let currentPath = "";
    for (const part of parts) {
      currentPath = currentPath ? `${currentPath}/${part}` : part;
      paths.push(currentPath);
    }
    return paths;
  }
  /**
   * Returns the vault path of the SCHEMA.md that would govern files in the
   * given folder. Empty/root folder yields a top-level SCHEMA.md.
   */
  schemaPathFor(folderPath) {
    if (folderPath === "" || folderPath === "/") {
      return SCHEMA_FILE_NAME;
    }
    return `${folderPath}/${SCHEMA_FILE_NAME}`;
  }
  isFileExcluded(file) {
    var _a;
    const patterns = this.settings.globalExcludePatterns;
    if (!patterns || patterns.length === 0) {
      return false;
    }
    const filePath = (_a = file.path) != null ? _a : "";
    return matchesExclusionPattern(filePath, patterns);
  }
};

// src/nanoid.ts
function generateNanoID(size = ID_CONFIG.length) {
  let id = "";
  const bytes = new Uint8Array(size);
  crypto.getRandomValues(bytes);
  for (let i = 0; i < size; i++) {
    id += ID_CONFIG.alphabet[bytes[i] % ID_CONFIG.alphabet.length];
  }
  return id;
}

// src/template-variables.ts
var import_obsidian4 = require("obsidian");
var VARIABLE_REGEX = /\{\{(\w+)\}\}/g;
var DEFAULT_DATE_FORMAT = "YYYY-MM-DD";
var DEFAULT_TIME_FORMAT = "HH:mm";
var VARIABLE_HANDLERS = {
  title: (context) => context.title,
  date: (context) => context.date,
  time: (context) => context.time,
  snowflakeId: (context) => context.snowflakeId
};
var TemplateVariableProcessor = class {
  constructor(dateFormat = DEFAULT_DATE_FORMAT, timeFormat = DEFAULT_TIME_FORMAT) {
    this.dateFormat = dateFormat;
    this.timeFormat = timeFormat;
  }
  /**
   * Process template content and replace all variables
   *
   * REQ-011: Replace {{title}}, {{date}}, {{time}}, {{snowflake_id}}
   * REQ-016: Ensure same ID value for multiple {{snowflake_id}} instances
   *
   * @param templateContent - The template content to process
   * @param file - The markdown file being created
   * @returns Processed content with variables replaced
   */
  processTemplate(templateContent, file) {
    const hasSnowflakeId = templateContent.includes("{{snowflake_id}}");
    const context = this.buildContext(file, hasSnowflakeId);
    const processedContent = this.replaceVariables(templateContent, context);
    return {
      content: processedContent,
      hasSnowflakeId,
      variables: context
    };
  }
  /**
   * Build the variable context for a file
   *
   * REQ-012: Use default date format "YYYY-MM-DD"
   * REQ-013: Use default time format "HH:mm"
   * REQ-014: Use custom formats if configured
   * REQ-015: Generate 10-character alphanumeric ID
   *
   * @param file - The file to build context for
   * @param generateId - Whether to generate a snowflake_id
   * @returns Variable context
   */
  buildContext(file, generateId) {
    const now = (0, import_obsidian4.moment)();
    const context = {
      title: file.basename,
      // filename without .md extension
      date: now.format(this.dateFormat),
      time: now.format(this.timeFormat)
    };
    if (generateId) {
      context.snowflakeId = generateNanoID();
    }
    return context;
  }
  /**
   * Replace all variables in the content
   *
   * REQ-027: If a template contains malformed variable syntax, then the
   * plugin shall leave it unchanged in the output.
   *
   * @param content - The content to process
   * @param context - The variable context
   * @returns Content with variables replaced
   */
  replaceVariables(content, context) {
    return content.replace(VARIABLE_REGEX, (match, varName) => {
      const handlerKey = varName === "snowflake_id" ? "snowflakeId" : varName;
      if (!(handlerKey in VARIABLE_HANDLERS)) {
        return match;
      }
      const handler = VARIABLE_HANDLERS[handlerKey];
      const value = handler(context);
      return value != null ? value : match;
    });
  }
  /**
   * Update date format
   *
   * REQ-014: Support custom date formats
   *
   * @param format - New date format
   */
  setDateFormat(format) {
    this.dateFormat = format !== "" ? format : DEFAULT_DATE_FORMAT;
  }
  /**
   * Update time format
   *
   * REQ-014: Support custom time formats
   *
   * @param format - New time format
   */
  setTimeFormat(format) {
    this.timeFormat = format !== "" ? format : DEFAULT_TIME_FORMAT;
  }
  /**
   * Validate a template for malformed variables
   *
   * REQ-028: When encountering invalid template variables, the plugin
   * shall show a warning to help users fix their templates.
   *
   * @param templateContent - The template to validate
   * @returns Array of invalid variable names found
   */
  validateTemplate(templateContent) {
    const invalidVars = [];
    const matches = templateContent.matchAll(VARIABLE_REGEX);
    for (const match of matches) {
      const varName = match[1];
      if (!(varName in VARIABLE_HANDLERS) && varName !== "snowflake_id") {
        invalidVars.push(varName);
      }
    }
    return [...new Set(invalidVars)];
  }
  /**
   * Get list of available variables
   *
   * @returns Array of variable names
   */
  getAvailableVariables() {
    return Object.keys(VARIABLE_HANDLERS);
  }
};

// src/frontmatter-merger.ts
var FRONTMATTER_REGEX = /^---\s*\n([\s\S]*?)\n---\s*$/m;
var FrontmatterMerger = class {
  /**
   * Merge two frontmatter sections
   *
   * REQ-008: Intelligently merge frontmatter blocks
   * REQ-009: Incoming values take precedence (except for lists)
   * REQ-010: Add new keys from incoming frontmatter
   * REQ-010a: Concatenate list-type fields (base first, then incoming)
   *
   * @param baseFrontmatter - The base frontmatter content
   * @param incomingFrontmatter - The incoming frontmatter to merge
   * @returns Merge result with conflicts and additions tracked
   */
  mergeFrontmatter(baseFrontmatter, incomingFrontmatter) {
    const baseFm = this.parseYaml(baseFrontmatter);
    const incomingFm = this.parseYaml(incomingFrontmatter);
    const conflicts = [];
    const added = [];
    const mergedData = { ...baseFm };
    for (const [key, value] of Object.entries(incomingFm)) {
      if (key in baseFm) {
        const baseVal = baseFm[key];
        const isBaseArray = Array.isArray(baseVal);
        const isIncomingArray = Array.isArray(value);
        const isBaseEmpty = baseVal === "" || baseVal === null || baseVal === void 0;
        const isIncomingEmpty = value === "" || value === null || value === void 0;
        if ((isBaseArray || isBaseEmpty) && (isIncomingArray || isIncomingEmpty)) {
          if (isBaseEmpty && isIncomingEmpty && !isBaseArray && !isIncomingArray) {
            mergedData[key] = "";
          } else {
            const baseArray = isBaseArray ? baseVal : [];
            const incomingArray = isIncomingArray ? value : [];
            mergedData[key] = this.concatenateArrays(baseArray, incomingArray);
          }
          conflicts.push(key);
        } else {
          mergedData[key] = value;
          conflicts.push(key);
        }
      } else {
        mergedData[key] = value;
        added.push(key);
      }
    }
    const mergedYaml = this.dataToYaml(mergedData);
    return {
      merged: mergedYaml,
      conflicts,
      added
    };
  }
  /**
   * Merge template frontmatter with existing file frontmatter
   *
   * Convenience method that extracts frontmatter from file content
   *
   * @param fileContent - The existing file content (may or may not have frontmatter)
   * @param templateFrontmatter - The template's frontmatter content
   * @returns Merge result with conflicts and additions tracked
   */
  mergeWithFile(fileContent, templateFrontmatter) {
    const fileFm = this.parseFrontmatter(fileContent);
    return this.mergeFrontmatter(templateFrontmatter, fileFm.content);
  }
  /**
   * Apply merged frontmatter to file content
   *
   * @param fileContent - Original file content
   * @param mergedFrontmatter - The merged frontmatter YAML
   * @returns File content with updated frontmatter
   */
  applyToFile(fileContent, mergedFrontmatter) {
    const parsed = this.parseFrontmatter(fileContent);
    const formattedFrontmatter = `---
${mergedFrontmatter}---`;
    if (parsed.exists && parsed.endPosition !== void 0) {
      return formattedFrontmatter + fileContent.slice(parsed.endPosition);
    } else {
      return formattedFrontmatter + "\n" + fileContent;
    }
  }
  /**
   * Parse frontmatter from file content
   *
   * @param content - File content
   * @returns Parsed frontmatter information
   */
  parseFrontmatter(content) {
    const match = content.match(FRONTMATTER_REGEX);
    if (!match) {
      return {
        exists: false,
        content: "",
        data: {}
      };
    }
    const frontmatterContent = match[1];
    const matchIndex = match.index;
    if (matchIndex === void 0) {
      return {
        exists: false,
        content: "",
        data: {}
      };
    }
    const endPosition = matchIndex + match[0].length;
    return {
      exists: true,
      content: frontmatterContent,
      data: this.parseYaml(frontmatterContent),
      endPosition
    };
  }
  /**
   * Parse YAML content into a data object
   *
   * This is a simple YAML parser that handles basic key-value pairs.
   * For more complex YAML structures, consider using a full YAML library.
   *
   * @param yaml - YAML content
   * @returns Parsed data object
   */
  parseYaml(yaml) {
    const data = {};
    const lines = yaml.split("\n");
    const state = this.createParserState();
    for (const line of lines) {
      this.processYamlLine(line, data, state);
    }
    this.savePendingValue(data, state);
    return data;
  }
  createParserState() {
    return { currentKey: null, currentValue: [] };
  }
  processYamlLine(line, data, state) {
    if (!line.trim() || line.trim().startsWith("#")) {
      return;
    }
    const keyMatch = line.match(/^([^:]+?):\s*(.*)$/);
    if (keyMatch) {
      this.handleKeyValueLine(keyMatch, data, state);
    } else if (state.currentKey !== null) {
      const arrayMatch = line.match(/^\s*- (.*)$/);
      if (arrayMatch) {
        if (!Array.isArray(data[state.currentKey])) {
          data[state.currentKey] = [];
        }
        const itemContent = arrayMatch[1].trim();
        if (itemContent === "") {
          data[state.currentKey].push("");
        } else {
          const itemValue = this.parseValue(itemContent);
          data[state.currentKey].push(itemValue);
        }
      } else if (line.startsWith("  ")) {
        state.currentValue.push(line.slice(2));
      }
    }
  }
  handleKeyValueLine(keyMatch, data, state) {
    this.savePendingValue(data, state);
    state.currentKey = keyMatch[1].trim();
    const value = keyMatch[2].trim();
    if (value === "|") {
      state.currentValue = [];
    } else if (value !== "") {
      data[state.currentKey] = this.parseValue(value);
      state.currentKey = null;
      state.currentValue = [];
    } else {
      state.currentValue = [];
    }
  }
  savePendingValue(data, state) {
    if (state.currentKey !== null) {
      if (state.currentValue.length > 0) {
        data[state.currentKey] = state.currentValue.join("\n").trim();
      } else if (!(state.currentKey in data)) {
        data[state.currentKey] = "";
      }
    }
  }
  /**
   * Parse a YAML value, handling basic types
   *
   * @param value - String value to parse
   * @returns Parsed value (string, number, boolean, or array)
   */
  parseValue(value) {
    const unquoted = this.tryUnquote(value);
    if (unquoted !== value) return unquoted;
    const booleanValue = this.tryParseBoolean(value);
    if (booleanValue !== void 0) return booleanValue;
    if (value === "null" || value === "~") return null;
    const numberValue = this.tryParseNumber(value);
    if (numberValue !== void 0) return numberValue;
    const arrayValue = this.tryParseArray(value);
    if (arrayValue !== void 0) return arrayValue;
    return value;
  }
  tryUnquote(value) {
    if (value.startsWith('"') && value.endsWith('"') || value.startsWith("'") && value.endsWith("'")) {
      return value.slice(1, -1);
    }
    return value;
  }
  tryParseBoolean(value) {
    if (value === "true") return true;
    if (value === "false") return false;
    return void 0;
  }
  tryParseNumber(value) {
    if (/^-?\d+(\.\d+)?$/.test(value)) {
      return parseFloat(value);
    }
    return void 0;
  }
  tryParseArray(value) {
    if (value.startsWith("[") && value.endsWith("]")) {
      const inner = value.slice(1, -1).trim();
      if (inner === "") {
        return [];
      }
      return inner.split(",").map((item) => this.parseValue(item.trim())).filter((item) => item !== "");
    }
    return void 0;
  }
  /**
   * Convert data object to YAML format
   *
   * @param data - Data object to convert
   * @returns YAML string
   */
  dataToYaml(data) {
    const lines = [];
    for (const [key, value] of Object.entries(data)) {
      const yamlLine = this.formatYamlLine(key, value);
      if (Array.isArray(yamlLine)) {
        lines.push(...yamlLine);
      } else {
        lines.push(yamlLine);
      }
    }
    return lines.join("\n") + "\n";
  }
  formatYamlLine(key, value) {
    if (value === null || value === void 0) {
      return `${key}: null`;
    }
    if (value === "") {
      return `${key}: `;
    }
    if (typeof value === "boolean" || typeof value === "number") {
      return `${key}: ${String(value)}`;
    }
    if (Array.isArray(value)) {
      if (value.length === 0) {
        return `${key}: []`;
      }
      const lines = [`${key}:`];
      for (const item of value) {
        lines.push(`  - ${this.formatValue(item)}`);
      }
      return lines;
    }
    if (typeof value === "string") {
      return this.formatStringValue(key, value);
    }
    if (typeof value === "object") {
      return `${key}: ${JSON.stringify(value)}`;
    }
    return `${key}: ${JSON.stringify(value)}`;
  }
  formatStringValue(key, value) {
    if (!value.includes("\n")) {
      return `${key}: ${this.formatValue(value)}`;
    }
    if (value.trim() === "|") {
      return `${key}: |`;
    }
    const lines = [`${key}: |`];
    const valueLines = value.split("\n");
    for (const line of valueLines) {
      lines.push(`  ${line}`);
    }
    return lines;
  }
  /**
   * Format a value for YAML output
   *
   * @param value - Value to format
   * @returns Formatted string
   */
  formatValue(value) {
    if (typeof value === "string") {
      if (value.startsWith('"') && value.endsWith('"') || value.startsWith("'") && value.endsWith("'")) {
        return value;
      }
      if (/[:[\]{},>|]/.test(value)) {
        return `"${value.replace(/"/g, '\\"')}"`;
      }
      return value;
    }
    return String(value);
  }
  /**
   * Concatenate two arrays with deduplication
   *
   * REQ-010a: When merging list-type fields, concatenate values
   * Preserves order: base array items first, then incoming items
   * Removes duplicates based on first occurrence
   *
   * @param baseArray - The base array
   * @param incomingArray - The array to concatenate
   * @returns Concatenated array with duplicates removed
   */
  concatenateArrays(baseArray, incomingArray) {
    const result = [];
    const seen = /* @__PURE__ */ new Set();
    const addUniqueItem = (item) => {
      const key = JSON.stringify(item);
      if (!seen.has(key)) {
        seen.add(key);
        result.push(item);
      }
    };
    for (const item of baseArray) {
      addUniqueItem(item);
    }
    for (const item of incomingArray) {
      addUniqueItem(item);
    }
    return result;
  }
  /**
   * Validate frontmatter syntax
   *
   * @param yaml - YAML content to validate
   * @returns True if valid, false otherwise
   */
  validateYaml(yaml) {
    try {
      const parsed = this.parseYaml(yaml);
      return typeof parsed === "object";
    } catch (e) {
      return false;
    }
  }
  /**
   * Extract delete list from frontmatter content
   *
   * REQ-034: Templates can have delete: [prop1, prop2] to exclude properties
   * REQ-037: The delete property defines exclusions for inheritance
   *
   * @param frontmatterContent - The frontmatter YAML content
   * @returns Array of property names to exclude, or null if no delete list
   */
  extractDeleteList(frontmatterContent) {
    const data = this.parseYaml(frontmatterContent);
    const deleteValue = data["delete"];
    if (deleteValue === void 0) {
      return null;
    }
    if (!Array.isArray(deleteValue)) {
      return null;
    }
    const validProperties = deleteValue.filter(
      (item) => typeof item === "string" && item.trim() !== ""
    );
    return validProperties.length > 0 ? validProperties : null;
  }
  /**
   * Apply delete list exclusions to frontmatter
   *
   * REQ-034: Remove properties listed in delete list
   * REQ-036: Always remove the "delete" property itself
   * REQ-037: Don't remove properties that are explicitly defined
   *
   * @param frontmatterContent - The frontmatter YAML content
   * @param deleteList - Array of property names to exclude
   * @param explicitlyDefined - Optional set of properties defined in current template
   * @returns Frontmatter with exclusions applied
   */
  applyDeleteList(frontmatterContent, deleteList, explicitlyDefined) {
    const data = this.parseYaml(frontmatterContent);
    const processedData = {};
    for (const [key, value] of Object.entries(data)) {
      if (key === "delete") {
        continue;
      }
      if (explicitlyDefined && explicitlyDefined.has(key)) {
        processedData[key] = value;
        continue;
      }
      if (deleteList.includes(key)) {
        continue;
      }
      processedData[key] = value;
    }
    return this.dataToYaml(processedData);
  }
  /**
   * Process frontmatter with delete list handling during template inheritance
   *
   * REQ-034: Apply delete list exclusions
   * REQ-035: Handle cumulative exclusions with override capability
   * REQ-036: Remove "delete" property from result
   * REQ-037: Explicit definitions override exclusions
   *
   * @param frontmatter - The frontmatter content to process
   * @param cumulativeDeleteList - Cumulative delete list from parent templates
   * @returns Processed result with delete list tracking
   */
  processWithDeleteList(frontmatter, cumulativeDeleteList = []) {
    const currentDeleteList = this.extractDeleteList(frontmatter) || [];
    const data = this.parseYaml(frontmatter);
    const explicitlyDefined = /* @__PURE__ */ new Set();
    for (const key of Object.keys(data)) {
      if (key !== "delete") {
        explicitlyDefined.add(key);
      }
    }
    const processedContent = this.applyDeleteList(
      frontmatter,
      cumulativeDeleteList,
      explicitlyDefined
    );
    const newDeleteList = [...cumulativeDeleteList];
    for (const prop of currentDeleteList) {
      if (!explicitlyDefined.has(prop) && !newDeleteList.includes(prop)) {
        newDeleteList.push(prop);
      }
    }
    return { processedContent, newDeleteList };
  }
  /**
   * Extract property names from frontmatter content
   *
   * @param frontmatterContent - The frontmatter YAML content
   * @returns Set of property names (excluding 'delete' property)
   */
  extractPropertyNames(frontmatterContent) {
    const data = this.parseYaml(frontmatterContent);
    const properties = /* @__PURE__ */ new Set();
    for (const key of Object.keys(data)) {
      if (key !== "delete") {
        properties.add(key);
      }
    }
    return properties;
  }
  /**
   * Check if a value is considered empty for cleanup purposes
   *
   * REQ-038: Empty values are: empty string, null, empty array
   * NOT empty: false, 0, undefined (undefined means property doesn't exist)
   *
   * @param value - The value to check
   * @returns True if the value is considered empty
   */
  isEmptyValue(value) {
    if (value === null) {
      return true;
    }
    if (typeof value === "string" && value.trim() === "") {
      return true;
    }
    if (Array.isArray(value) && value.length === 0) {
      return true;
    }
    return false;
  }
  /**
   * Clean up empty properties that don't come from templates
   *
   * REQ-038: Remove properties that are empty and not from template chain
   *
   * @param frontmatterContent - The merged frontmatter content
   * @param templateProperties - Set of properties that came from templates
   * @returns Cleaned frontmatter content
   */
  cleanupEmptyProperties(frontmatterContent, templateProperties) {
    const data = this.parseYaml(frontmatterContent);
    const cleanedData = {};
    for (const [key, value] of Object.entries(data)) {
      const isFromTemplate = templateProperties.has(key);
      const isEmpty = this.isEmptyValue(value);
      if (isFromTemplate || !isEmpty) {
        cleanedData[key] = value;
      }
    }
    const result = this.dataToYaml(cleanedData);
    return result;
  }
  /**
   * Merge template frontmatter with accumulated frontmatter considering delete lists
   *
   * This method handles the complete merge process including:
   * - Extracting and managing cumulative delete lists
   * - Tracking explicitly defined properties
   * - Applying delete lists after merging
   *
   * @param accumulatedFrontmatter - The accumulated frontmatter from parent templates
   * @param currentTemplateFrontmatter - The current template's frontmatter
   * @param cumulativeDeleteList - The cumulative delete list from parent templates
   * @returns Object containing merged frontmatter and updated delete list
   */
  mergeWithDeleteList(accumulatedFrontmatter, currentTemplateFrontmatter, cumulativeDeleteList) {
    const currentDeleteList = this.extractDeleteList(currentTemplateFrontmatter);
    const data = this.parseYaml(currentTemplateFrontmatter);
    const explicitlyDefined = new Set(Object.keys(data).filter((k) => k !== "delete"));
    const updatedDeleteList = cumulativeDeleteList.filter((prop) => !explicitlyDefined.has(prop));
    if (currentDeleteList) {
      for (const prop of currentDeleteList) {
        if (!explicitlyDefined.has(prop) && !updatedDeleteList.includes(prop)) {
          updatedDeleteList.push(prop);
        }
      }
    }
    const deleteResult = this.processWithDeleteList(
      currentTemplateFrontmatter,
      cumulativeDeleteList
    );
    const mergeResult = this.mergeFrontmatter(
      accumulatedFrontmatter,
      deleteResult.processedContent
    );
    const mergedFrontmatter = this.applyDeleteList(
      mergeResult.merged,
      updatedDeleteList,
      explicitlyDefined
    );
    return { mergedFrontmatter, updatedDeleteList };
  }
};

// src/template-applicator.ts
var TemplateApplicator = class {
  constructor(vault, settings) {
    this.vault = vault;
    this.loader = new TemplateLoader(vault, settings);
    this.variableProcessor = new TemplateVariableProcessor(
      settings.dateFormat,
      settings.timeFormat
    );
    this.frontmatterMerger = new FrontmatterMerger();
    this.errorHandler = ErrorHandler.getInstance();
  }
  /**
   * Apply a template to a file
   *
   * REQ-025: Manual commands always work
   *
   * @param file - The file to apply template to
   * @param context - Command context (manual vs automatic)
   * @param editor - Optional editor for cursor position
   * @returns Application result
   */
  async applyTemplate(file, context = { isManualCommand: false }, editor) {
    const chain = this.loader.getTemplateChain(file);
    if (chain.templates.length === 0) {
      return { success: false, message: "No SCHEMA.md found for this location" };
    }
    const loadedChain = await this.loader.loadTemplateChain(chain);
    if (loadedChain.templates.length === 0) {
      return { success: false, message: "No templates could be loaded" };
    }
    const finalTemplateContent = this.mergeTemplates(loadedChain.templates);
    const templateProperties = this.extractPropertiesFromFinalTemplate(finalTemplateContent);
    const result = await this.applyProcessedTemplateContent(
      file,
      finalTemplateContent,
      templateProperties,
      editor,
      context
    );
    if (result.success && context.isBatchOperation !== true) {
      const templateNames = loadedChain.templates.map((t) => t.path).join(" \u2192 ");
      console.info(`Snowflake: Template(s) "${templateNames}" applied to ${file.path}`);
    }
    return result;
  }
  /**
   * Apply processed template content to a file
   *
   * REQ-006: Merge template with existing content
   * REQ-007: Insert body at cursor position
   * REQ-039: Apply only frontmatter in batch operations
   *
   * @param file - The file to apply to
   * @param processedContent - The processed template content
   * @param editor - Optional editor for cursor position
   * @param context - Command context with batch operation flag
   * @returns Application result
   */
  async applyProcessedTemplate(file, processedContent, editor, context) {
    const currentContent = await this.vault.read(file);
    const templateParts = this.splitContent(processedContent);
    const currentParts = this.splitContent(currentContent);
    const { content: contentAfterFrontmatter, updatedBody } = this.processFrontmatter(
      currentContent,
      templateParts,
      currentParts
    );
    const isBatchOperation = (context == null ? void 0 : context.isBatchOperation) === true;
    const shouldSkipBody = isBatchOperation && updatedBody.trim() !== "";
    let finalContent;
    if (shouldSkipBody) {
      finalContent = contentAfterFrontmatter;
    } else {
      finalContent = this.processBodyContent(
        contentAfterFrontmatter,
        templateParts.body,
        updatedBody,
        editor
      );
    }
    const normalizedContent = finalContent.trimEnd() + "\n";
    await this.vault.modify(file, normalizedContent);
    return { success: true, message: "Template applied successfully" };
  }
  processFrontmatter(currentContent, templateParts, currentParts) {
    if (templateParts.frontmatter === null || templateParts.frontmatter === "") {
      return { content: currentContent, updatedBody: currentParts.body };
    }
    const mergeResult = this.frontmatterMerger.mergeWithFile(
      currentContent,
      templateParts.frontmatter
    );
    const contentWithMergedFrontmatter = this.frontmatterMerger.applyToFile(
      currentContent,
      mergeResult.merged
    );
    const newParts = this.splitContent(contentWithMergedFrontmatter);
    return { content: contentWithMergedFrontmatter, updatedBody: newParts.body };
  }
  processBodyContent(currentContent, templateBody, currentBody, editor) {
    if (templateBody === "") {
      return currentContent;
    }
    if (currentBody === "" || editor === void 0) {
      const trimmedContent = currentContent.trimEnd();
      const trimmedTemplate = templateBody.trimEnd();
      if (trimmedContent !== "") {
        return trimmedContent + "\n" + trimmedTemplate;
      }
      return trimmedTemplate;
    }
    return this.insertAtCursor(currentContent, templateBody, currentBody, editor);
  }
  insertAtCursor(currentContent, templateBody, currentBody, editor) {
    const cursor = editor.getCursor();
    const lines = currentBody.split("\n");
    const trimmedTemplateBody = templateBody.trimEnd();
    if (cursor.line < lines.length) {
      lines[cursor.line] = lines[cursor.line].slice(0, cursor.ch) + trimmedTemplateBody + lines[cursor.line].slice(cursor.ch);
    } else {
      lines.push(trimmedTemplateBody);
    }
    const parts = this.splitContent(currentContent);
    return parts.frontmatterBlock + lines.join("\n");
  }
  /**
   * Split content into frontmatter and body parts
   *
   * @param content - Content to split
   * @returns Split content parts
   */
  splitContent(content) {
    const frontmatterMatch = content.match(/^---\s*\n([\s\S]*?)\n---\s*\n?/);
    if (frontmatterMatch) {
      return {
        frontmatter: frontmatterMatch[1],
        frontmatterBlock: frontmatterMatch[0],
        body: content.slice(frontmatterMatch[0].length)
      };
    }
    return {
      frontmatter: null,
      frontmatterBlock: "",
      body: content
    };
  }
  /**
   * Apply processed template content with empty property cleanup
   *
   * REQ-038: Remove empty properties not from templates
   * REQ-039: Apply only frontmatter in batch operations
   *
   * @param file - The file to apply to
   * @param templateContent - The raw template content
   * @param templateProperties - Properties from the template chain
   * @param editor - Optional editor for cursor position
   * @param context - Command context with batch operation flag
   * @returns Application result
   */
  async applyProcessedTemplateContent(file, templateContent, templateProperties, editor, context) {
    try {
      const currentContent = await this.vault.read(file);
      const hasExistingContent = currentContent.trim() !== "";
      const processedTemplate = this.variableProcessor.processTemplate(templateContent, file);
      const result = await this.applyProcessedTemplate(
        file,
        processedTemplate.content,
        editor,
        context
      );
      if (result.success && hasExistingContent) {
        await this.cleanupEmptyProperties(file, templateProperties);
      }
      return {
        ...result,
        hadSnowflakeId: processedTemplate.hasSnowflakeId
      };
    } catch (error) {
      const errorContext = {
        operation: "apply_template",
        filePath: file.path
      };
      const errorMessage = this.errorHandler.handleError(error, errorContext);
      return {
        success: false,
        message: errorMessage
      };
    }
  }
  /**
   * Update settings reference
   *
   * @param settings - New settings
   */
  updateSettings(settings) {
    this.loader.updateSettings(settings);
    this.variableProcessor.setDateFormat(settings.dateFormat);
    this.variableProcessor.setTimeFormat(settings.timeFormat);
  }
  /**
   * Merge multiple templates into a single template
   *
   * REQ-033: Merge templates with child templates taking precedence
   * REQ-033a: Concatenate list-type fields across inheritance chain
   *
   * @param templates - Templates to merge (ordered from root to leaf)
   * @returns Merged template content
   */
  mergeTemplates(templates) {
    if (templates.length === 0) {
      return "";
    }
    const { frontmatter, body } = this.accumulateTemplateContent(templates);
    return this.formatMergedContent(frontmatter, body);
  }
  /**
   * Accumulate frontmatter and body content from templates
   *
   * REQ-034: Apply delete list exclusions from templates
   * REQ-035: Track cumulative delete list through inheritance chain
   * REQ-036: Remove "delete" property from final result
   * REQ-037: Allow explicit redefinition to override exclusions
   */
  accumulateTemplateContent(templates) {
    let accumulatedFrontmatter = "";
    let accumulatedBody = "";
    let cumulativeDeleteList = [];
    for (const template of templates) {
      if (template.content === void 0 || template.content === "") {
        continue;
      }
      const parts = this.splitContent(template.content);
      if (parts.frontmatter !== null && parts.frontmatter.trim() !== "") {
        if (accumulatedFrontmatter === "") {
          const deleteResult = this.frontmatterMerger.processWithDeleteList(
            parts.frontmatter,
            cumulativeDeleteList
          );
          accumulatedFrontmatter = deleteResult.processedContent;
          cumulativeDeleteList = deleteResult.newDeleteList;
        } else {
          const result = this.frontmatterMerger.mergeWithDeleteList(
            accumulatedFrontmatter,
            parts.frontmatter,
            cumulativeDeleteList
          );
          accumulatedFrontmatter = result.mergedFrontmatter;
          cumulativeDeleteList = result.updatedDeleteList;
        }
      }
      if (parts.body.trim() !== "") {
        if (accumulatedBody !== "") {
          accumulatedBody += "\n\n";
        }
        accumulatedBody += parts.body.trim();
      }
    }
    return { frontmatter: accumulatedFrontmatter, body: accumulatedBody };
  }
  /**
   * Format merged frontmatter and body into final content
   */
  formatMergedContent(frontmatter, body) {
    if (frontmatter !== "") {
      const trimmedFrontmatter = frontmatter.trimEnd();
      let mergedContent = `---
${trimmedFrontmatter}
---`;
      if (body !== "") {
        mergedContent += "\n" + body;
      }
      return mergedContent;
    }
    return body;
  }
  /**
   * Extract property names from the final merged template
   *
   * REQ-038: Track properties that actually exist in the final template after delete lists
   *
   * @param finalTemplateContent - The final merged template content
   * @returns Set of property names in the final template
   */
  extractPropertiesFromFinalTemplate(finalTemplateContent) {
    const parts = this.splitContent(finalTemplateContent);
    if (parts.frontmatter !== null && parts.frontmatter.trim() !== "") {
      const properties = this.frontmatterMerger.extractPropertyNames(parts.frontmatter);
      return properties;
    }
    return /* @__PURE__ */ new Set();
  }
  /**
   * Clean up empty properties not from templates
   *
   * REQ-038: Remove empty properties that weren't added by template chain
   *
   * @param file - The file to clean up
   * @param templateProperties - Properties from the template chain
   */
  async cleanupEmptyProperties(file, templateProperties) {
    const content = await this.vault.read(file);
    const parts = this.splitContent(content);
    if (parts.frontmatter !== null && parts.frontmatter.trim() !== "") {
      const cleanedFrontmatter = this.frontmatterMerger.cleanupEmptyProperties(
        parts.frontmatter,
        templateProperties
      );
      if (cleanedFrontmatter !== parts.frontmatter) {
        const cleanedContent = `---
${cleanedFrontmatter}---
${parts.body}`;
        const normalizedContent = cleanedContent.trimEnd() + "\n";
        await this.vault.modify(file, normalizedContent);
      }
    }
  }
};

// src/file-creation-handler.ts
var FileCreationHandler = class {
  constructor(plugin, vault, settings) {
    this.processingQueue = /* @__PURE__ */ new Set();
    this.createEventRef = null;
    this.renameEventRef = null;
    this.plugin = plugin;
    this.vault = vault;
    this.settings = settings;
    this.templateApplicator = new TemplateApplicator(vault, settings);
    this.errorHandler = ErrorHandler.getInstance();
  }
  /**
   * Start listening for file creation and rename/move events
   */
  start() {
    this.createEventRef = this.vault.on("create", (file) => {
      if (file instanceof import_obsidian5.TFile) {
        this.handleFileCreation(file).catch(() => {
        });
      }
    });
    this.plugin.registerEvent(this.createEventRef);
    this.renameEventRef = this.vault.on("rename", (file, oldPath) => {
      if (file instanceof import_obsidian5.TFile) {
        this.handleFileMove(file, oldPath).catch(() => {
        });
      }
    });
    this.plugin.registerEvent(this.renameEventRef);
  }
  /**
   * Stop listening for file events
   */
  stop() {
    if (this.createEventRef !== null) {
      this.vault.offref(this.createEventRef);
      this.createEventRef = null;
    }
    if (this.renameEventRef !== null) {
      this.vault.offref(this.renameEventRef);
      this.renameEventRef = null;
    }
    this.processingQueue.clear();
  }
  /**
   * Handle file creation event
   *
   * REQ-004: Check if file is markdown before processing
   *
   * @param file - The newly created file
   */
  async handleFileCreation(file) {
    await this.processFile(file);
  }
  /**
   * Common method to process a file for template application
   *
   * @param file - The file to process
   */
  async processFile(file) {
    if (!isMarkdownFile(file)) {
      return;
    }
    if (file.name === SCHEMA_FILE_NAME) {
      return;
    }
    if (this.processingQueue.has(file.path)) {
      return;
    }
    this.processingQueue.add(file.path);
    try {
      await this.asyncProcessFile(file);
    } finally {
      this.processingQueue.delete(file.path);
    }
  }
  async asyncProcessFile(file) {
    const stillExists = this.vault.getAbstractFileByPath(file.path);
    if (!stillExists) {
      return;
    }
    let content;
    try {
      content = await this.vault.read(file);
    } catch (e) {
      return;
    }
    if (content.trim() !== "") {
      return;
    }
    try {
      const context = { isManualCommand: false };
      await this.templateApplicator.applyTemplate(file, context);
    } catch (error) {
      const errorContext = {
        operation: "apply_template",
        filePath: file.path
      };
      this.errorHandler.handleErrorSilently(error, errorContext);
    }
  }
  /**
   * Handle file move/rename event
   *
   * @param file - The file that was moved
   * @param oldPath - The previous path of the file
   */
  async handleFileMove(file, oldPath) {
    const oldDirIndex = oldPath.lastIndexOf("/");
    const newDirIndex = file.path.lastIndexOf("/");
    const oldDir = oldDirIndex === -1 ? "" : oldPath.substring(0, oldDirIndex);
    const newDir = newDirIndex === -1 ? "" : file.path.substring(0, newDirIndex);
    if (oldDir === newDir) {
      return;
    }
    await this.processFile(file);
  }
  /**
   * Update settings reference
   *
   * @param settings - New settings
   */
  updateSettings(settings) {
    this.settings = settings;
    this.templateApplicator.updateSettings(settings);
  }
  /**
   * Check if a file is currently being processed
   *
   * @param filePath - Path to check
   * @returns True if file is in processing queue
   */
  isProcessing(filePath) {
    return this.processingQueue.has(filePath);
  }
  /**
   * Get the number of files currently being processed
   *
   * @returns Number of files in processing queue
   */
  getProcessingCount() {
    return this.processingQueue.size;
  }
};

// src/commands.ts
var import_obsidian8 = require("obsidian");

// src/ui/confirmation-modal.ts
var import_obsidian6 = require("obsidian");
var ConfirmationModal = class extends import_obsidian6.Modal {
  constructor(app, title, message, onConfirm, onCancel) {
    super(app);
    this.title = title;
    this.message = message;
    this.onConfirm = onConfirm;
    this.onCancel = onCancel;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: this.title });
    contentEl.createEl("p", { text: this.message });
    new import_obsidian6.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Cancel").onClick(() => {
        this.close();
        this.onCancel();
      })
    ).addButton(
      (btn) => btn.setButtonText("Confirm").setCta().onClick(() => {
        this.close();
        this.onConfirm();
      })
    );
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/ui/folder-modal.ts
var import_obsidian7 = require("obsidian");
var FolderSuggestModal = class extends import_obsidian7.FuzzySuggestModal {
  constructor(app, onChoose) {
    super(app);
    this.onChoose = onChoose;
  }
  getItems() {
    const folders = [];
    const rootFolder = this.app.vault.getRoot();
    folders.push(rootFolder);
    const addFolders = (folder) => {
      for (const child of folder.children) {
        if (child instanceof import_obsidian7.TFolder) {
          folders.push(child);
          addFolders(child);
        }
      }
    };
    addFolders(rootFolder);
    return folders;
  }
  getItemText(folder) {
    return folder.path || "/";
  }
  onChooseItem(folder, _evt) {
    this.onChoose(folder);
  }
};

// src/commands.ts
var SnowflakeCommands = class {
  constructor(plugin, settings) {
    this.plugin = plugin;
    this.settings = settings;
    this.templateApplicator = new TemplateApplicator(plugin.app.vault, settings);
    this.errorHandler = ErrorHandler.getInstance();
  }
  registerCommands() {
    this.plugin.addCommand({
      id: "apply-schema-to-current-note",
      name: "Apply schema to current note",
      editorCallback: (editor, view) => {
        this.applyTemplateToCurrentNote(editor, view).catch(() => {
        });
      }
    });
    this.plugin.addCommand({
      id: "insert-date",
      name: "Insert current date",
      editorCallback: (editor) => {
        this.insertDate(editor);
      }
    });
    this.plugin.addCommand({
      id: "insert-time",
      name: "Insert current time",
      editorCallback: (editor) => {
        this.insertTime(editor);
      }
    });
    this.plugin.addCommand({
      id: "create-note-in-folder",
      name: "Create new note in folder",
      callback: () => {
        this.createNoteInFolder();
      }
    });
  }
  async applyTemplateToCurrentNote(editor, view) {
    const file = "file" in view ? view.file : view;
    if (!file) {
      new import_obsidian8.Notice("No active file");
      return;
    }
    if (!isMarkdownFile(file)) {
      new import_obsidian8.Notice("Current file is not a markdown file");
      return;
    }
    const context = { isManualCommand: true };
    try {
      const result = await this.templateApplicator.applyTemplate(file, context, editor);
      if (!result.success) {
        new import_obsidian8.Notice(result.message);
      }
    } catch (error) {
      const errorContext = {
        operation: "apply_template",
        filePath: file.path
      };
      this.errorHandler.handleError(error, errorContext);
    }
  }
  async processFolderBatch(folder, skipConfirmation = false) {
    const markdownFiles = this.getMarkdownFiles(folder);
    if (markdownFiles.length === 0) {
      if (!skipConfirmation) {
        new import_obsidian8.Notice("No markdown files found in selected folder");
      }
      return null;
    }
    if (!skipConfirmation) {
      const confirmed = await this.confirmBatchOperation(folder, markdownFiles.length);
      if (!confirmed) {
        return null;
      }
    }
    const result = await this.processFilesInBatches(markdownFiles);
    if (!skipConfirmation) {
      this.showCompletionNotice(result);
    }
    return result;
  }
  async applyTemplateToFolderPath(folderPath, skipConfirmation = false) {
    const folder = this.plugin.app.vault.getAbstractFileByPath(folderPath);
    if (!folder || !(folder instanceof import_obsidian8.TFolder)) {
      if (!skipConfirmation) {
        new import_obsidian8.Notice(`Folder not found: ${folderPath}`);
      }
      return null;
    }
    return await this.processFolderBatch(folder, skipConfirmation);
  }
  getMarkdownFiles(folder) {
    const markdownFiles = [];
    this.collectMarkdownFiles(folder, markdownFiles);
    return markdownFiles;
  }
  async processFilesInBatches(files) {
    const batchSize = 10;
    const context = { isManualCommand: true, isBatchOperation: true };
    let successCount = 0;
    for (let i = 0; i < files.length; i += batchSize) {
      const batch = files.slice(i, i + batchSize);
      const results = await this.processBatch(batch, context);
      successCount += results.reduce((sum, val) => sum + val, 0);
      await this.sleep(10);
    }
    return {
      success: successCount,
      total: files.length
    };
  }
  async processBatch(batch, context) {
    return Promise.all(
      batch.map(
        (file) => this.templateApplicator.applyTemplate(file, context).then((result) => result.success ? 1 : 0).catch((error) => {
          const errorContext = {
            operation: "apply_template",
            filePath: file.path
          };
          this.errorHandler.handleErrorSilently(error, errorContext);
          return 0;
        })
      )
    );
  }
  showCompletionNotice(result) {
    if (result.success === result.total) {
      new import_obsidian8.Notice(`Templates applied to ${String(result.success)} notes`);
    } else {
      new import_obsidian8.Notice(`Templates applied to ${String(result.success)} of ${String(result.total)} notes`);
    }
  }
  confirmBatchOperation(folder, fileCount) {
    return new Promise((resolve) => {
      const modal = new ConfirmationModal(
        this.plugin.app,
        `Apply templates to ${String(fileCount)} notes in "${folder.path}"?`,
        "This will apply the appropriate template to all markdown files in this folder.",
        () => {
          resolve(true);
        },
        () => {
          resolve(false);
        }
      );
      modal.open();
    });
  }
  collectMarkdownFiles(folder, files) {
    for (const child of folder.children) {
      if (child instanceof import_obsidian8.TFile && isMarkdownFile(child)) {
        files.push(child);
      } else if (child instanceof import_obsidian8.TFolder) {
        this.collectMarkdownFiles(child, files);
      }
    }
  }
  sleep(ms) {
    return new Promise((resolve) => {
      setTimeout(resolve, ms);
    });
  }
  updateSettings(settings) {
    this.settings = settings;
    this.templateApplicator.updateSettings(settings);
  }
  insertDate(editor) {
    const date = window.moment().format(this.settings.dateFormat);
    editor.replaceSelection(date);
  }
  insertTime(editor) {
    const time = window.moment().format(this.settings.timeFormat);
    editor.replaceSelection(time);
  }
  createNoteInFolder() {
    const modal = new FolderSuggestModal(this.plugin.app, (folder) => {
      this.createNoteInFolderHandler(folder).catch(() => {
      });
    });
    modal.open();
  }
  async createNoteInFolderHandler(folder) {
    try {
      let fileName = "Untitled";
      let counter = 1;
      let filePath = folder.path ? `${folder.path}/${fileName}.md` : `${fileName}.md`;
      while (this.plugin.app.vault.getAbstractFileByPath(filePath)) {
        fileName = `Untitled ${String(counter)}`;
        filePath = folder.path ? `${folder.path}/${fileName}.md` : `${fileName}.md`;
        counter++;
      }
      const file = await this.plugin.app.vault.create(filePath, "");
      const leaf = this.plugin.app.workspace.getLeaf();
      await leaf.openFile(file);
      setTimeout(() => {
        const view = this.plugin.app.workspace.getActiveViewOfType(import_obsidian8.MarkdownView);
        if (view) {
          const titleEl = view.containerEl.querySelector(".inline-title");
          if (titleEl) {
            titleEl.focus();
            const range = document.createRange();
            range.selectNodeContents(titleEl);
            const selection = window.getSelection();
            if (selection) {
              selection.removeAllRanges();
              selection.addRange(range);
            }
          }
        }
      }, 100);
    } catch (error) {
      const errorContext = {
        operation: "apply_template",
        filePath: folder.path || "/"
      };
      this.errorHandler.handleError(error, errorContext);
    }
  }
};

// src/main.ts
var SnowflakePlugin = class extends import_obsidian9.Plugin {
  async onload() {
    await this.loadSettings();
    this.commands = new SnowflakeCommands(this, this.settings);
    this.commands.registerCommands();
    this.addSettingTab(new SnowflakeSettingTab(this.app, this));
    this.fileCreationHandler = new FileCreationHandler(this, this.app.vault, this.settings);
    this.app.workspace.onLayoutReady(() => {
      var _a;
      (_a = this.fileCreationHandler) == null ? void 0 : _a.start();
    });
  }
  onunload() {
    if (this.fileCreationHandler !== void 0) {
      this.fileCreationHandler.stop();
    }
  }
  async loadSettings() {
    const data = await this.loadData();
    if (areSettingsValid(data)) {
      this.settings = data;
    } else {
      this.settings = migrateSettings(data);
    }
    this.validateSettings();
    await this.saveSettings();
  }
  async saveSettings() {
    this.settings = cleanSettings(this.settings);
    this.validateSettings();
    const configDir = this.manifest.dir;
    if (configDir !== void 0 && configDir !== "") {
      const configPath = `${configDir}/data.json`;
      const content = JSON.stringify(this.settings, null, 2) + "\n";
      await this.app.vault.adapter.write(configPath, content);
    } else {
      await this.saveData(this.settings);
    }
    if (this.fileCreationHandler !== void 0) {
      this.fileCreationHandler.updateSettings(this.settings);
    }
    if (this.commands !== void 0) {
      this.commands.updateSettings(this.settings);
    }
  }
  validateSettings() {
    if (typeof this.settings.dateFormat !== "string" || this.settings.dateFormat.trim() === "") {
      this.settings.dateFormat = "YYYY-MM-DD";
    }
    if (typeof this.settings.timeFormat !== "string" || this.settings.timeFormat.trim() === "") {
      this.settings.timeFormat = "HH:mm";
    }
    if (!Array.isArray(this.settings.globalExcludePatterns)) {
      this.settings.globalExcludePatterns = [];
    }
  }
};
