/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  SnowflakePlugin: () => SnowflakePlugin,
  default: () => SnowflakePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian14 = require("obsidian");

// src/ui/settings-tab.ts
var import_obsidian7 = require("obsidian");

// src/ui/folder-input-suggest.ts
var import_obsidian = require("obsidian");
var FolderInputSuggest = class extends import_obsidian.AbstractInputSuggest {
  constructor(app, inputEl) {
    super(app, inputEl);
    this.inputEl = inputEl;
  }
  getSuggestions(query) {
    const lowerQuery = query.toLowerCase();
    const allFolders = this.app.vault.getAllLoadedFiles().filter((file) => file instanceof import_obsidian.TFolder);
    if (!query) {
      return allFolders.filter((folder) => !folder.parent || folder.parent === this.app.vault.getRoot()).sort((a, b) => a.name.localeCompare(b.name)).slice(0, 10);
    }
    return allFolders.filter((folder) => {
      const path = folder.path.toLowerCase();
      const name = folder.name.toLowerCase();
      return path.includes(lowerQuery) || name.includes(lowerQuery);
    }).sort((a, b) => {
      const aNameMatch = a.name.toLowerCase() === lowerQuery;
      const bNameMatch = b.name.toLowerCase() === lowerQuery;
      if (aNameMatch && !bNameMatch) return -1;
      if (!aNameMatch && bNameMatch) return 1;
      const aStartsWith = a.name.toLowerCase().startsWith(lowerQuery);
      const bStartsWith = b.name.toLowerCase().startsWith(lowerQuery);
      if (aStartsWith && !bStartsWith) return -1;
      if (!aStartsWith && bStartsWith) return 1;
      return a.path.length - b.path.length;
    }).slice(0, 10);
  }
  renderSuggestion(folder, el) {
    el.setText(folder.path);
    el.addClass("folder-suggestion-item");
  }
  selectSuggestion(folder, _evt) {
    this.inputEl.value = folder.path;
    this.inputEl.trigger("input");
    this.close();
  }
};

// src/ui/template-mapping-modal.ts
var import_obsidian3 = require("obsidian");

// src/ui/file-input-suggest.ts
var import_obsidian2 = require("obsidian");
var FileInputSuggest = class extends import_obsidian2.AbstractInputSuggest {
  constructor(app, inputEl, fileExtension = "md", rootFolder) {
    super(app, inputEl);
    this.inputEl = inputEl;
    this.fileExtension = fileExtension;
    this.rootFolder = rootFolder;
  }
  getSuggestions(query) {
    const lowerQuery = query.toLowerCase();
    let allFiles = this.app.vault.getAllLoadedFiles().filter(
      (file) => file instanceof import_obsidian2.TFile && file.extension === this.fileExtension
    );
    if (this.rootFolder !== void 0 && this.rootFolder !== "") {
      const rootPath = this.rootFolder;
      allFiles = allFiles.filter((file) => file.path.startsWith(rootPath + "/"));
    }
    if (!query) {
      return allFiles.sort((a, b) => a.path.localeCompare(b.path)).slice(0, 10);
    }
    return this.filterAndSortFiles(allFiles, lowerQuery).slice(0, 10);
  }
  filterAndSortFiles(files, lowerQuery) {
    return files.filter((file) => {
      const path = file.path.toLowerCase();
      const basename = file.basename.toLowerCase();
      return path.includes(lowerQuery) || basename.includes(lowerQuery);
    }).sort((a, b) => {
      const aNameMatch = a.basename.toLowerCase() === lowerQuery;
      const bNameMatch = b.basename.toLowerCase() === lowerQuery;
      if (aNameMatch && !bNameMatch) return -1;
      if (!aNameMatch && bNameMatch) return 1;
      const aStartsWith = a.basename.toLowerCase().startsWith(lowerQuery);
      const bStartsWith = b.basename.toLowerCase().startsWith(lowerQuery);
      if (aStartsWith && !bStartsWith) return -1;
      if (!aStartsWith && bStartsWith) return 1;
      return a.path.length - b.path.length;
    });
  }
  renderSuggestion(file, el) {
    el.createDiv({ cls: "suggestion-content" }, (contentEl) => {
      contentEl.createDiv({ cls: "suggestion-title", text: file.basename });
      contentEl.createDiv({ cls: "suggestion-path", text: file.path });
    });
  }
  selectSuggestion(file, _evt) {
    if (this.rootFolder !== void 0 && file.path.startsWith(this.rootFolder + "/")) {
      this.inputEl.value = file.path.slice(this.rootFolder.length + 1);
    } else {
      this.inputEl.value = file.path;
    }
    this.inputEl.trigger("input");
    this.close();
  }
};

// src/pattern-matcher.ts
function matchesExclusionPattern(filePath, patterns) {
  var _a;
  if (!patterns || patterns.length === 0) {
    return false;
  }
  const fileName = (_a = filePath.split("/").pop()) != null ? _a : filePath;
  return patterns.some((pattern) => {
    if (!pattern || pattern.trim() === "") {
      return false;
    }
    if (pattern.endsWith("/")) {
      const dirPath = pattern.slice(0, -1);
      return filePath.startsWith(dirPath + "/") || filePath === dirPath;
    }
    if (pattern === filePath || pattern === fileName) {
      return true;
    }
    const regexPattern = globToRegex(pattern);
    return regexPattern.test(filePath) || regexPattern.test(fileName);
  });
}
function globToRegex(glob) {
  let pattern = glob.replace(/[.+^${}()|[\]\\]/g, "\\$&");
  pattern = pattern.replace(/\*\*/g, "{{DOUBLESTAR}}").replace(/\*/g, "[^/]*").replace(/\?/g, ".").replace(/{{DOUBLESTAR}}/g, ".*");
  pattern = "^" + pattern + "$";
  return new RegExp(pattern);
}
function normalizePattern(pattern) {
  pattern = pattern.trim();
  if (pattern.startsWith("/")) {
    pattern = pattern.slice(1);
  }
  return pattern;
}
function processExclusionPatterns(input) {
  if (!input || input.trim() === "") {
    return {
      patterns: [],
      isValid: true,
      errors: []
    };
  }
  const rawPatterns = input.split("\n");
  const normalizedPatterns = [];
  const errors = [];
  rawPatterns.forEach((pattern, index) => {
    const normalized = normalizePattern(pattern);
    if (normalized === "") {
      return;
    }
    if (pattern.includes("\0")) {
      errors.push(`Line ${String(index + 1)}: Pattern contains invalid null character`);
      return;
    }
    normalizedPatterns.push(normalized);
  });
  return {
    patterns: normalizedPatterns,
    isValid: errors.length === 0,
    errors
  };
}

// src/ui/template-mapping-modal.ts
var TemplateMappingModal = class extends import_obsidian3.Modal {
  constructor(app, templatesFolder, onSave, editData) {
    super(app);
    this.folderPath = "";
    this.templatePath = "";
    this.excludePatterns = "";
    this.templatesFolder = templatesFolder;
    this.onSave = onSave;
    if (editData) {
      this.isEditMode = true;
      this.originalFolderPath = editData.folderPath;
      this.folderPath = editData.folderPath;
      if (typeof editData.config === "string") {
        this.templatePath = editData.config;
      } else {
        this.templatePath = editData.config.templatePath;
        if (editData.config.excludePatterns && editData.config.excludePatterns.length > 0) {
          this.excludePatterns = editData.config.excludePatterns.join("\n");
        }
      }
    } else {
      this.isEditMode = false;
    }
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", {
      text: this.isEditMode ? "Edit Template Mapping" : "Add Template Mapping"
    });
    contentEl.createEl("p", {
      text: this.isEditMode ? "Modify the folder mapping configuration" : "Map a folder to a template file",
      cls: "setting-item-description"
    });
    new import_obsidian3.Setting(contentEl).setName("Folder").setDesc("Select the folder to map (leave empty for root folder)").addText((text) => {
      new FolderInputSuggest(this.app, text.inputEl);
      text.setPlaceholder("Example: Projects (empty for root)").setValue(this.folderPath).onChange((value) => {
        this.folderPath = value;
        this.updateSaveButton();
      });
      if (this.isEditMode) {
        setTimeout(() => {
          text.inputEl.blur();
        }, 0);
      }
      return text;
    });
    new import_obsidian3.Setting(contentEl).setName("Template").setDesc("Select the template file to use").addText((text) => {
      new FileInputSuggest(this.app, text.inputEl, "md", this.templatesFolder);
      text.setPlaceholder("Example: project.md").setValue(this.templatePath).onChange((value) => {
        this.templatePath = value;
        this.updateSaveButton();
      });
      return text;
    });
    new import_obsidian3.Setting(contentEl).setName("Exclude Files (optional)").setDesc("Enter patterns to exclude files from template application. One pattern per line.").addTextArea((text) => {
      text.setPlaceholder("*.tmp\ndraft-*\nREADME.md").setValue(this.excludePatterns).onChange((value) => {
        this.excludePatterns = value;
      });
      text.inputEl.rows = 4;
      text.inputEl.style.width = "100%";
      return text;
    });
    new import_obsidian3.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Cancel").onClick(() => {
        this.close();
      })
    ).addButton((btn) => {
      this.saveButton = btn.setButtonText(this.isEditMode ? "Save" : "Add").setCta().onClick(() => {
        this.handleSave();
      }).buttonEl;
      this.updateSaveButton();
      return btn;
    });
  }
  updateSaveButton() {
    if (this.saveButton) {
      this.saveButton.disabled = !this.templatePath;
    }
  }
  handleSave() {
    if (!this.templatePath) {
      new import_obsidian3.Notice("Please select a template");
      return;
    }
    const result = processExclusionPatterns(this.excludePatterns);
    if (!result.isValid) {
      const errorMessage = result.errors.join("\n");
      new import_obsidian3.Notice(`Invalid exclusion patterns:
${errorMessage}`, 5e3);
      return;
    }
    this.onSave(
      this.folderPath,
      this.templatePath,
      result.patterns.length > 0 ? result.patterns : void 0,
      this.isEditMode ? this.originalFolderPath : void 0
    );
    this.close();
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/ui/confirmation-modal.ts
var import_obsidian4 = require("obsidian");
var ConfirmationModal = class extends import_obsidian4.Modal {
  constructor(app, title, message, onConfirm, onCancel) {
    super(app);
    this.title = title;
    this.message = message;
    this.onConfirm = onConfirm;
    this.onCancel = onCancel;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: this.title });
    contentEl.createEl("p", { text: this.message });
    new import_obsidian4.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Cancel").onClick(() => {
        this.close();
        this.onCancel();
      })
    ).addButton(
      (btn) => btn.setButtonText("Confirm").setCta().onClick(() => {
        this.close();
        this.onConfirm();
      })
    );
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/ui/template-preview-modal.ts
var import_obsidian5 = require("obsidian");
var TemplatePreviewModal = class extends import_obsidian5.Modal {
  constructor(app, templatePath, content) {
    super(app);
    this.templatePath = templatePath;
    this.content = content;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: `Preview: ${this.templatePath}` });
    const pre = contentEl.createEl("pre", {
      cls: "template-preview-content"
    });
    pre.createEl("code", {
      cls: "language-markdown",
      text: this.content
    });
    pre.style.maxHeight = "400px";
    pre.style.overflow = "auto";
    pre.style.backgroundColor = "var(--background-secondary)";
    pre.style.padding = "1em";
    pre.style.borderRadius = "4px";
    const buttonContainer = contentEl.createDiv({ cls: "modal-button-container" });
    buttonContainer.createEl("button", {
      text: "Close",
      cls: "mod-cta"
    }).addEventListener("click", () => {
      this.close();
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/error-handler.ts
var import_obsidian6 = require("obsidian");
var ErrorHandler = class _ErrorHandler {
  constructor() {
    this.debugMode = false;
  }
  /**
   * Get singleton instance
   */
  static getInstance() {
    var _a;
    (_a = _ErrorHandler.instance) != null ? _a : _ErrorHandler.instance = new _ErrorHandler();
    return _ErrorHandler.instance;
  }
  /**
   * Enable/disable debug mode
   */
  setDebugMode(enabled) {
    this.debugMode = enabled;
  }
  /**
   * Handle an error with appropriate user feedback
   *
   * @param error - The error to handle
   * @param context - Context about where the error occurred
   * @returns User-friendly error message
   */
  handleError(error, context) {
    const errorType = this.categorizeError(error);
    const userMessage = this.getUserMessage(errorType, context, error);
    this.logError(error, context, errorType);
    new import_obsidian6.Notice(userMessage);
    return userMessage;
  }
  /**
   * Handle error without showing notice (for cases where caller handles UI)
   */
  handleErrorSilently(error, context) {
    const errorType = this.categorizeError(error);
    const userMessage = this.getUserMessage(errorType, context, error);
    this.logError(error, context, errorType);
    return userMessage;
  }
  /**
   * Categorize the error type
   */
  categorizeError(error) {
    if (error === null || error === void 0) return "UNKNOWN" /* UNKNOWN */;
    const errorMessage = this.getErrorMessage(error).toLowerCase();
    if (this.isFileNotFoundError(errorMessage)) {
      return "FILE_NOT_FOUND" /* FILE_NOT_FOUND */;
    }
    if (this.isPermissionError(errorMessage)) {
      return "PERMISSION_DENIED" /* PERMISSION_DENIED */;
    }
    if (this.isTemplateSyntaxError(errorMessage)) {
      return "INVALID_TEMPLATE_SYNTAX" /* INVALID_TEMPLATE_SYNTAX */;
    }
    if (this.isVariableError(errorMessage)) {
      return "INVALID_VARIABLE" /* INVALID_VARIABLE */;
    }
    return "UNKNOWN" /* UNKNOWN */;
  }
  getErrorMessage(error) {
    if (error instanceof Error) {
      return error.message;
    }
    return String(error);
  }
  isFileNotFoundError(message) {
    return message.includes("file not found") || message.includes("enoent") || message.includes("no such file");
  }
  isPermissionError(message) {
    return message.includes("permission") || message.includes("eacces") || message.includes("access denied");
  }
  isTemplateSyntaxError(message) {
    return message.includes("invalid template") || message.includes("template syntax");
  }
  isVariableError(message) {
    return message.includes("invalid variable") || message.includes("unknown variable");
  }
  /**
   * Get user-friendly error message based on error type and context
   */
  getUserMessage(errorType, context, error) {
    switch (errorType) {
      case "TEMPLATE_NOT_FOUND" /* TEMPLATE_NOT_FOUND */:
        return this.getTemplateNotFoundMessage(context);
      case "FILE_NOT_FOUND" /* FILE_NOT_FOUND */:
        return this.getFileNotFoundMessage(context);
      case "PERMISSION_DENIED" /* PERMISSION_DENIED */:
        return this.getPermissionDeniedMessage(context);
      case "INVALID_TEMPLATE_SYNTAX" /* INVALID_TEMPLATE_SYNTAX */:
        return this.getInvalidSyntaxMessage(context);
      case "INVALID_VARIABLE" /* INVALID_VARIABLE */:
        return this.getInvalidVariableMessage(context);
      case "MERGE_CONFLICT" /* MERGE_CONFLICT */:
        return "Error merging frontmatter. Using existing content.";
      default:
        return this.getGenericErrorMessage(context, error);
    }
  }
  getTemplateNotFoundMessage(context) {
    var _a;
    const path = (_a = context.templatePath) != null ? _a : "unknown";
    return `Template not found: ${path}. Creating file without template.`;
  }
  getFileNotFoundMessage(context) {
    var _a, _b;
    if (context.operation === "load_template") {
      return `Template file not found: ${(_a = context.templatePath) != null ? _a : "unknown"}`;
    }
    return `File not found: ${(_b = context.filePath) != null ? _b : "unknown"}`;
  }
  getPermissionDeniedMessage(context) {
    var _a, _b, _c;
    if (context.operation === "load_template") {
      const path2 = (_a = context.templatePath) != null ? _a : "unknown";
      return `Cannot read template (permission denied): ${path2}. Creating file without template.`;
    }
    const path = (_c = (_b = context.filePath) != null ? _b : context.templatePath) != null ? _c : "unknown";
    return `Permission denied accessing: ${path}`;
  }
  getInvalidSyntaxMessage(context) {
    var _a;
    const path = (_a = context.templatePath) != null ? _a : "unknown";
    return `Template contains invalid syntax and will be used as-is: ${path}`;
  }
  getInvalidVariableMessage(context) {
    var _a;
    const path = (_a = context.templatePath) != null ? _a : "unknown";
    return `Template contains invalid variables that will be left unchanged: ${path}`;
  }
  getGenericErrorMessage(context, error) {
    const operation = this.getOperationDescription(context.operation);
    const errorMessage = error instanceof Error ? error.message : "Unknown error";
    return `Error ${operation}: ${errorMessage}`;
  }
  /**
   * Get human-readable operation description
   */
  getOperationDescription(operation) {
    switch (operation) {
      case "load_template":
        return "loading template";
      case "apply_template":
        return "applying template";
      case "merge_frontmatter":
        return "merging frontmatter";
      default:
        return "processing";
    }
  }
  /**
   * Log error for debugging
   */
  logError(error, context, errorType) {
    const logMessage = {
      timestamp: (/* @__PURE__ */ new Date()).toISOString(),
      errorType,
      context,
      error: error instanceof Error ? {
        message: error.message,
        stack: error.stack,
        name: error.name
      } : String(error)
    };
    console.error("[Snowflake Plugin Error]", logMessage);
    if (this.debugMode) {
      console.error("[Snowflake Debug] Full error details:", error);
    }
  }
  /**
   * Create an ExtendedError with context
   */
  createError(message, type, context, originalError) {
    const error = new Error(message);
    error.type = type;
    error.context = context;
    error.originalError = originalError;
    return error;
  }
  /**
   * Check if an error is a specific type
   */
  isErrorType(error, type) {
    if (error !== null && error !== void 0 && typeof error === "object" && "type" in error) {
      return error.type === type;
    }
    return false;
  }
};

// src/ui/settings-tab.ts
var SnowflakeSettingTab = class extends import_obsidian7.PluginSettingTab {
  constructor(app, plugin, commands) {
    super(app, plugin);
    this.plugin = plugin;
    this.errorHandler = ErrorHandler.getInstance();
    this.commands = commands;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    this.addHeader(containerEl);
    this.addGeneralSettings(containerEl);
    this.addGlobalExcludeSettings(containerEl);
    this.addTemplateMappings(containerEl);
    this.addVariableFormatSettings(containerEl);
    this.addHelpSection(containerEl);
  }
  addHeader(containerEl) {
    containerEl.createEl("h1", { text: "Snowflake Settings" });
    containerEl.createEl("p", {
      text: "Configure automatic template application for new notes.",
      cls: "setting-item-description"
    });
  }
  addGeneralSettings(containerEl) {
    containerEl.createEl("h2", { text: "General Settings" });
    this.addTemplatesFolderSetting(containerEl);
  }
  addGlobalExcludeSettings(containerEl) {
    containerEl.createEl("h2", {
      text: "Global Exclude Patterns"
    });
    containerEl.createEl("p", {
      text: "Files matching these patterns will be ignored by all template mappings. One pattern per line.",
      cls: "setting-item-description"
    });
    const patterns = this.plugin.settings.globalExcludePatterns;
    const currentValue = patterns.length > 0 ? patterns.join("\n") : "";
    new import_obsidian7.Setting(containerEl).setName("Exclude patterns").setDesc(
      "Glob patterns: * matches characters, ** matches directories, ? matches single character"
    ).addTextArea((text) => {
      text.setPlaceholder("*.tmp\n_archive/**\n~*.md").setValue(currentValue).onChange(async (value) => {
        const result = processExclusionPatterns(value);
        this.plugin.settings.globalExcludePatterns = result.patterns;
        await this.plugin.saveSettings();
      });
      text.inputEl.rows = 4;
      text.inputEl.cols = 30;
      return text;
    });
  }
  addTemplatesFolderSetting(containerEl) {
    new import_obsidian7.Setting(containerEl).setName("Templates folder").setDesc("The folder where your template files are stored").addText((text) => {
      new FolderInputSuggest(this.app, text.inputEl);
      text.setPlaceholder("Templates").setValue(this.plugin.settings.templatesFolder).onChange(async (value) => {
        this.plugin.settings.templatesFolder = value || "Templates";
        await this.plugin.saveSettings();
      });
      setTimeout(() => {
        text.inputEl.blur();
      }, 0);
      return text;
    });
  }
  addVariableFormatSettings(containerEl) {
    containerEl.createEl("h2", { text: "Variable Formats" });
    containerEl.createEl("p", {
      text: "Customize the format for date and time variables in templates",
      cls: "setting-item-description"
    });
    new import_obsidian7.Setting(containerEl).setName("Date format").setDesc("Format for {{date}} variable (uses moment.js format)").addText((text) => {
      var _a;
      text.setPlaceholder("YYYY-MM-DD").setValue(this.plugin.settings.dateFormat);
      const preview = (_a = text.inputEl.parentElement) == null ? void 0 : _a.createDiv({
        cls: "setting-item-description",
        text: `Preview: ${window.moment().format(this.plugin.settings.dateFormat)}`
      });
      text.onChange(async (value) => {
        const format = value || "YYYY-MM-DD";
        this.plugin.settings.dateFormat = format;
        await this.plugin.saveSettings();
        if (preview) {
          try {
            preview.textContent = `Preview: ${window.moment().format(format)}`;
          } catch (e) {
            preview.textContent = "Preview: Invalid format";
          }
        }
      });
      return text;
    });
    new import_obsidian7.Setting(containerEl).setName("Time format").setDesc("Format for {{time}} variable (uses moment.js format)").addText((text) => {
      var _a;
      text.setPlaceholder("HH:mm").setValue(this.plugin.settings.timeFormat);
      const preview = (_a = text.inputEl.parentElement) == null ? void 0 : _a.createDiv({
        cls: "setting-item-description",
        text: `Preview: ${window.moment().format(this.plugin.settings.timeFormat)}`
      });
      text.onChange(async (value) => {
        const format = value || "HH:mm";
        this.plugin.settings.timeFormat = format;
        await this.plugin.saveSettings();
        if (preview) {
          try {
            preview.textContent = `Preview: ${window.moment().format(format)}`;
          } catch (e) {
            preview.textContent = "Preview: Invalid format";
          }
        }
      });
      return text;
    });
    containerEl.createEl("p", {
      cls: "setting-item-description",
      text: "Common formats: YYYY-MM-DD, DD/MM/YYYY, MMM DD YYYY, HH:mm:ss, h:mm A"
    });
  }
  addTemplateMappings(containerEl) {
    containerEl.createEl("h2", { text: "Folder Template Mappings" });
    containerEl.createEl("p", {
      text: "Configure which template to use for each folder",
      cls: "setting-item-description"
    });
    const mappings = Object.entries(this.plugin.settings.templateMappings);
    if (mappings.length === 0) {
      this.showNoMappingsMessage(containerEl);
    } else {
      this.showExistingMappings(containerEl, mappings);
    }
    this.addNewMappingButton(containerEl);
    if (mappings.length >= 2) {
      this.addApplyAllButton(containerEl);
    }
  }
  showNoMappingsMessage(containerEl) {
    containerEl.createEl("p", {
      text: "No folder mappings configured. Click 'Add mapping' to get started.",
      cls: "setting-item-description mod-warning"
    });
  }
  showExistingMappings(containerEl, mappings) {
    mappings.sort((a, b) => a[0].localeCompare(b[0]));
    mappings.forEach(([folderPath, config]) => {
      this.createMappingSetting(containerEl, folderPath, config);
    });
  }
  createMappingSetting(containerEl, folderPath, config) {
    const templatePath = typeof config === "string" ? config : config.templatePath;
    const excludePatterns = typeof config === "object" ? config.excludePatterns : void 0;
    const setting = new import_obsidian7.Setting(containerEl);
    const nameEl = setting.nameEl;
    nameEl.createSpan({ text: folderPath || "/ (root folder)" });
    if (excludePatterns && excludePatterns.length > 0) {
      nameEl.createSpan({
        text: ` (${String(excludePatterns.length)} exclusion${excludePatterns.length > 1 ? "s" : ""})`,
        cls: "snowflake-exclusion-count"
      });
    }
    setting.setDesc(templatePath);
    setting.addButton(
      (button) => button.setIcon("eye").setTooltip("Preview template").onClick(async () => {
        await this.previewTemplate(templatePath);
      })
    );
    setting.addButton(
      (button) => button.setIcon("play").setTooltip("Apply template to all notes in folder").onClick(async () => {
        await this.commands.applyTemplateToFolderPath(folderPath);
      })
    );
    setting.addButton(
      (button) => button.setIcon("pencil").setTooltip("Edit mapping").onClick(() => {
        this.showEditMappingDialog(folderPath, config);
      })
    );
    setting.addButton(
      (button) => button.setButtonText("Remove").setWarning().onClick(async () => {
        delete this.plugin.settings.templateMappings[folderPath];
        await this.plugin.saveSettings();
        this.display();
        new import_obsidian7.Notice(`Removed mapping for ${folderPath || "root folder"}`);
      })
    );
  }
  addApplyAllButton(containerEl) {
    new import_obsidian7.Setting(containerEl).setName("Apply all mappings").setDesc("Apply templates to all mapped folders").addButton(
      (button) => button.setButtonText("Apply All").setTooltip("Apply templates to all mapped folders").onClick(() => {
        this.applyAllMappings();
      })
    );
  }
  addNewMappingButton(containerEl) {
    new import_obsidian7.Setting(containerEl).setName("Add folder mapping").setDesc("Map a folder to a specific template").addButton(
      (button) => button.setButtonText("Add Mapping").setCta().onClick(() => {
        this.showAddMappingDialog();
      })
    );
  }
  addHelpSection(containerEl) {
    containerEl.createEl("h2", { text: "Template Variables" });
    containerEl.createEl("p", {
      text: "You can use these variables in your templates:",
      cls: "setting-item-description"
    });
    const variableList = containerEl.createEl("ul", {
      cls: "setting-item-description"
    });
    variableList.createEl("li", { text: "{{title}} - The filename without extension" });
    variableList.createEl("li", {
      text: `{{date}} - Current date (using your format: ${this.plugin.settings.dateFormat})`
    });
    variableList.createEl("li", {
      text: `{{time}} - Current time (using your format: ${this.plugin.settings.timeFormat})`
    });
    variableList.createEl("li", { text: "{{snowflake_id}} - Unique 10-character ID" });
  }
  /**
   * Show dialog to add a new folder mapping
   */
  showAddMappingDialog() {
    new TemplateMappingModal(
      this.app,
      this.plugin.settings.templatesFolder,
      (folderPath, templatePath, excludePatterns, originalFolderPath) => {
        if (!originalFolderPath && folderPath in this.plugin.settings.templateMappings) {
          new import_obsidian7.Notice("This folder already has a template mapping");
          return;
        }
        if (excludePatterns && excludePatterns.length > 0) {
          this.plugin.settings.templateMappings[folderPath] = {
            templatePath,
            excludePatterns
          };
        } else {
          this.plugin.settings.templateMappings[folderPath] = templatePath;
        }
        void this.plugin.saveSettings();
        this.display();
        new import_obsidian7.Notice(`Mapped ${folderPath || "root folder"} to ${templatePath}`);
      }
    ).open();
  }
  /**
   * Show dialog to edit an existing folder mapping
   */
  showEditMappingDialog(folderPath, config) {
    new TemplateMappingModal(
      this.app,
      this.plugin.settings.templatesFolder,
      (newFolderPath, templatePath, excludePatterns, originalFolderPath) => {
        if (originalFolderPath && newFolderPath !== originalFolderPath && newFolderPath in this.plugin.settings.templateMappings) {
          new import_obsidian7.Notice("This folder already has a template mapping");
          return;
        }
        if (originalFolderPath && newFolderPath !== originalFolderPath) {
          delete this.plugin.settings.templateMappings[originalFolderPath];
        }
        if (excludePatterns && excludePatterns.length > 0) {
          this.plugin.settings.templateMappings[newFolderPath] = {
            templatePath,
            excludePatterns
          };
        } else {
          this.plugin.settings.templateMappings[newFolderPath] = templatePath;
        }
        void this.plugin.saveSettings();
        this.display();
        new import_obsidian7.Notice(`Updated mapping for ${newFolderPath || "root folder"}`);
      },
      {
        folderPath,
        config
      }
    ).open();
  }
  /**
   * Preview a template file
   */
  async previewTemplate(templatePath) {
    const fullPath = templatePath.startsWith(this.plugin.settings.templatesFolder + "/") ? templatePath : `${this.plugin.settings.templatesFolder}/${templatePath}`;
    const file = this.app.vault.getAbstractFileByPath(fullPath);
    if (!file || !(file instanceof import_obsidian7.TFile)) {
      new import_obsidian7.Notice(`Template not found: ${fullPath}`);
      return;
    }
    try {
      const content = await this.app.vault.read(file);
      new TemplatePreviewModal(this.app, templatePath, content).open();
    } catch (error) {
      const errorContext = {
        operation: "load_template",
        templatePath
      };
      this.errorHandler.handleError(error, errorContext);
    }
  }
  /**
   * Apply templates to all mapped folders
   */
  applyAllMappings() {
    const mappings = Object.entries(this.plugin.settings.templateMappings);
    if (mappings.length === 0) {
      new import_obsidian7.Notice("No template mappings configured");
      return;
    }
    new ConfirmationModal(
      this.app,
      "Apply All Template Mappings",
      `This will apply templates to all notes in ${String(mappings.length)} mapped folder${mappings.length > 1 ? "s" : ""}. Are you sure you want to continue?`,
      () => {
        void (async () => {
          let totalSuccess = 0;
          let totalFiles = 0;
          for (const [folderPath] of mappings) {
            const result = await this.commands.applyTemplateToFolderPath(folderPath, true);
            if (result) {
              totalSuccess += result.success;
              totalFiles += result.total;
            }
          }
          if (totalFiles === 0) {
            new import_obsidian7.Notice("No markdown files found in selected folders");
          } else if (totalSuccess === totalFiles) {
            new import_obsidian7.Notice(`Templates applied to ${String(totalSuccess)} notes`);
          } else {
            new import_obsidian7.Notice(
              `Templates applied to ${String(totalSuccess)} of ${String(totalFiles)} notes`
            );
          }
        })();
      },
      () => {
      }
    ).open();
  }
};

// src/constants.ts
var DEFAULT_SETTINGS = {
  // Folder-specific template assignments (REQ-002)
  templateMappings: {},
  // Base directory where templates are stored
  templatesFolder: "Templates",
  // Date format for {{date}} variable (uses moment.js format)
  dateFormat: "YYYY-MM-DD",
  // Time format for {{time}} variable (uses moment.js format)
  timeFormat: "HH:mm",
  // Global exclusion patterns applied to all template mappings
  globalExcludePatterns: []
};
var ID_CONFIG = {
  // Length of generated IDs
  length: 10,
  // Alphabet of 62 alphanumeric characters
  // Includes: lowercase, uppercase, numbers
  // Excludes: Special characters (no dashes or underscores)
  alphabet: "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
};

// src/settings-utils.ts
function isValidTemplateMapping(value) {
  if (value === null || value === void 0 || typeof value !== "object") {
    return false;
  }
  return Object.entries(value).every(([key, val]) => {
    if (typeof key !== "string") return false;
    if (typeof val === "string") return true;
    if (typeof val === "object" && val !== null && "templatePath" in val) {
      const config = val;
      if (typeof config.templatePath !== "string") return false;
      if ("excludePatterns" in config) {
        if (!Array.isArray(config.excludePatterns)) return false;
        return config.excludePatterns.every((p) => typeof p === "string");
      }
      return true;
    }
    return false;
  });
}
function areSettingsValid(settings) {
  if (settings === null || settings === void 0 || typeof settings !== "object") {
    return false;
  }
  const s = settings;
  if (!("templateMappings" in s && isValidTemplateMapping(s.templateMappings) && "templatesFolder" in s && typeof s.templatesFolder === "string" && "dateFormat" in s && typeof s.dateFormat === "string" && "timeFormat" in s && typeof s.timeFormat === "string")) {
    return false;
  }
  if ("globalExcludePatterns" in s) {
    if (!Array.isArray(s.globalExcludePatterns)) {
      return false;
    }
    if (!s.globalExcludePatterns.every((p) => typeof p === "string")) {
      return false;
    }
  }
  return true;
}
function migrateSettings(settings) {
  if (areSettingsValid(settings)) {
    return cleanSettings(settings);
  }
  if (settings !== null && settings !== void 0 && typeof settings === "object") {
    const s = settings;
    const migrated = { ...DEFAULT_SETTINGS };
    if ("templateMappings" in s && isValidTemplateMapping(s.templateMappings)) {
      migrated.templateMappings = s.templateMappings;
    }
    if ("templatesFolder" in s && typeof s.templatesFolder === "string" && s.templatesFolder.trim() !== "") {
      migrated.templatesFolder = s.templatesFolder;
    }
    if ("dateFormat" in s && typeof s.dateFormat === "string" && s.dateFormat.trim() !== "") {
      migrated.dateFormat = s.dateFormat;
    }
    if ("timeFormat" in s && typeof s.timeFormat === "string" && s.timeFormat.trim() !== "") {
      migrated.timeFormat = s.timeFormat;
    }
    if ("globalExcludePatterns" in s && Array.isArray(s.globalExcludePatterns) && s.globalExcludePatterns.every((p) => typeof p === "string")) {
      migrated.globalExcludePatterns = s.globalExcludePatterns;
    }
    return migrated;
  }
  return { ...DEFAULT_SETTINGS };
}
function cleanSettings(settings) {
  const cleaned = {
    templateMappings: settings.templateMappings,
    templatesFolder: settings.templatesFolder,
    dateFormat: settings.dateFormat || DEFAULT_SETTINGS.dateFormat,
    timeFormat: settings.timeFormat || DEFAULT_SETTINGS.timeFormat,
    globalExcludePatterns: settings.globalExcludePatterns || DEFAULT_SETTINGS.globalExcludePatterns
  };
  return cleaned;
}

// src/file-creation-handler.ts
var import_obsidian10 = require("obsidian");

// src/types.ts
function isMarkdownFile(file) {
  return file.extension === "md";
}

// src/template-loader.ts
var import_obsidian8 = require("obsidian");
var TemplateLoader = class {
  constructor(vault, settings) {
    this.vault = vault;
    this.settings = settings;
    this.errorHandler = ErrorHandler.getInstance();
  }
  /**
   * Load a template file by path
   *
   * REQ-026: Handle missing template files gracefully
   *
   * @param templatePath - Path to the template file
   * @returns Template content or null if not found
   */
  async loadTemplate(templatePath) {
    try {
      const templateFile = this.vault.getAbstractFileByPath(templatePath);
      if (!templateFile || !(templateFile instanceof import_obsidian8.TFile)) {
        console.warn(`Template not found: ${templatePath}`);
        return null;
      }
      const content = await this.vault.read(templateFile);
      return content;
    } catch (error) {
      const errorContext = {
        operation: "load_template",
        templatePath
      };
      this.errorHandler.handleErrorSilently(error, errorContext);
      return null;
    }
  }
  /**
   * Get the template path for a file based on its location
   *
   * REQ-002: Use folder-specific template mapping
   * REQ-003: Fall back to default template
   *
   * @param file - The file to get template for
   * @returns Template path or null if no template configured
   */
  getTemplateForFile(file) {
    var _a, _b, _c;
    const folderPath = (_b = (_a = file.parent) == null ? void 0 : _a.path) != null ? _b : "";
    const mapping = this.settings.templateMappings[folderPath];
    if (mapping !== void 0) {
      if (this.isFileExcluded(file, folderPath, mapping)) {
        return null;
      }
      return this.resolveTemplatePathFromMapping(mapping);
    }
    let currentPath = folderPath;
    while (currentPath.includes("/")) {
      currentPath = currentPath.substring(0, currentPath.lastIndexOf("/"));
      const parentMapping = this.settings.templateMappings[currentPath];
      if (parentMapping !== void 0) {
        if (this.isFileExcluded(file, currentPath, parentMapping)) {
          return null;
        }
        return this.resolveTemplatePathFromMapping(parentMapping);
      }
    }
    const rootMapping = (_c = this.settings.templateMappings[""]) != null ? _c : this.settings.templateMappings["/"];
    if (rootMapping !== void 0) {
      if (this.isFileExcluded(file, "", rootMapping)) {
        return null;
      }
      return this.resolveTemplatePathFromMapping(rootMapping);
    }
    return null;
  }
  /**
   * Validate that a template path exists
   *
   * @param templatePath - Path to validate
   * @returns True if template exists
   */
  templateExists(templatePath) {
    const file = this.vault.getAbstractFileByPath(templatePath);
    return file instanceof import_obsidian8.TFile;
  }
  /**
   * Get all available template files in the templates folder
   *
   * @returns Array of template file paths
   */
  getAvailableTemplates() {
    const templates = [];
    const templatesFolder = this.settings.templatesFolder;
    const folder = this.vault.getAbstractFileByPath(templatesFolder);
    if (!folder) {
      return templates;
    }
    if (!("children" in folder)) {
      return templates;
    }
    const collectTemplates = (abstractFile) => {
      if (abstractFile instanceof import_obsidian8.TFile && abstractFile.extension === "md") {
        templates.push(abstractFile.path);
      } else if (abstractFile instanceof import_obsidian8.TFolder) {
        for (const child of abstractFile.children) {
          collectTemplates(child);
        }
      }
    };
    const abstractFolder = folder;
    collectTemplates(abstractFolder);
    return templates;
  }
  /**
   * Update settings reference (for when settings change)
   *
   * @param settings - New settings object
   */
  updateSettings(settings) {
    this.settings = settings;
  }
  /**
   * Get the template chain for a file based on its location
   *
   * REQ-032: Check parent folders for template mappings and apply them
   * in order from root to leaf
   *
   * @param file - The file to get template chain for
   * @returns Template chain with all applicable templates
   */
  getTemplateChain(file) {
    var _a;
    const templates = [];
    const folderPaths = this.getFolderHierarchy(file);
    for (let i = 0; i < folderPaths.length; i++) {
      const folderPath = folderPaths[i];
      const mapping = this.settings.templateMappings[folderPath];
      if (mapping !== void 0) {
        if (!this.isFileExcluded(file, folderPath, mapping)) {
          templates.push({
            path: this.resolveTemplatePathFromMapping(mapping),
            folderPath,
            depth: i
          });
        }
      }
    }
    if (templates.length === 0) {
      const rootMapping = (_a = this.settings.templateMappings[""]) != null ? _a : this.settings.templateMappings["/"];
      if (rootMapping !== void 0) {
        if (!this.isFileExcluded(file, "", rootMapping)) {
          templates.push({
            path: this.resolveTemplatePathFromMapping(rootMapping),
            folderPath: "",
            depth: 0
          });
        }
      }
    }
    return {
      templates,
      hasInheritance: templates.length > 1
    };
  }
  /**
   * Load content for all templates in a chain
   *
   * REQ-032: Handle missing templates gracefully
   *
   * @param chain - Template chain to load
   * @returns Template chain with content populated
   */
  async loadTemplateChain(chain) {
    const loadedTemplates = [];
    for (const template of chain.templates) {
      const content = await this.loadTemplate(template.path);
      if (content !== null) {
        loadedTemplates.push({
          ...template,
          content
        });
      } else {
        console.warn(`Skipping missing template in chain: ${template.path}`);
      }
    }
    return {
      templates: loadedTemplates,
      hasInheritance: loadedTemplates.length > 1
    };
  }
  /**
   * Get folder hierarchy from a file's location
   *
   * @param file - File to get hierarchy for
   * @returns Array of folder paths from root to immediate parent
   */
  getFolderHierarchy(file) {
    var _a;
    const paths = [];
    paths.push("");
    const folderPath = (_a = file.parent) == null ? void 0 : _a.path;
    if (folderPath === void 0 || folderPath === "" || folderPath === "/") {
      return paths;
    }
    const parts = folderPath.split("/").filter((p) => p !== "");
    let currentPath = "";
    for (const part of parts) {
      currentPath = currentPath ? `${currentPath}/${part}` : part;
      paths.push(currentPath);
    }
    return paths;
  }
  /**
   * Check if a file is excluded by global or mapping exclusion patterns
   *
   * @param file - The file to check
   * @param mappingFolderPath - The folder path of the mapping
   * @param mapping - The template mapping configuration
   * @returns True if the file should be excluded
   */
  isFileExcluded(file, mappingFolderPath, mapping) {
    var _a;
    const filePath = (_a = file.path) != null ? _a : "";
    let relativePath;
    if (mappingFolderPath === "") {
      relativePath = filePath;
    } else if (filePath.startsWith(mappingFolderPath + "/")) {
      relativePath = filePath.slice(mappingFolderPath.length + 1);
    } else {
      relativePath = file.name;
    }
    const globalPatterns = this.settings.globalExcludePatterns;
    if (globalPatterns && globalPatterns.length > 0) {
      if (matchesExclusionPattern(relativePath, globalPatterns)) {
        return true;
      }
      if (relativePath !== filePath && matchesExclusionPattern(filePath, globalPatterns)) {
        return true;
      }
    }
    if (typeof mapping === "string") {
      return false;
    }
    if (!mapping.excludePatterns || mapping.excludePatterns.length === 0) {
      return false;
    }
    return matchesExclusionPattern(relativePath, mapping.excludePatterns);
  }
  /**
   * Resolve template path from a mapping
   *
   * @param mapping - The template mapping (string or config object)
   * @returns Resolved template path
   */
  resolveTemplatePathFromMapping(mapping) {
    const templatePath = typeof mapping === "string" ? mapping : mapping.templatePath;
    return `${this.settings.templatesFolder}/${templatePath}`;
  }
};

// src/nanoid.ts
function generateNanoID(size = ID_CONFIG.length) {
  let id = "";
  const bytes = new Uint8Array(size);
  crypto.getRandomValues(bytes);
  for (let i = 0; i < size; i++) {
    id += ID_CONFIG.alphabet[bytes[i] % ID_CONFIG.alphabet.length];
  }
  return id;
}

// src/template-variables.ts
var import_obsidian9 = require("obsidian");
var VARIABLE_REGEX = /\{\{(\w+)\}\}/g;
var DEFAULT_DATE_FORMAT = "YYYY-MM-DD";
var DEFAULT_TIME_FORMAT = "HH:mm";
var VARIABLE_HANDLERS = {
  title: (context) => context.title,
  date: (context) => context.date,
  time: (context) => context.time,
  snowflakeId: (context) => context.snowflakeId
};
var TemplateVariableProcessor = class {
  constructor(dateFormat = DEFAULT_DATE_FORMAT, timeFormat = DEFAULT_TIME_FORMAT) {
    this.dateFormat = dateFormat;
    this.timeFormat = timeFormat;
  }
  /**
   * Process template content and replace all variables
   *
   * REQ-011: Replace {{title}}, {{date}}, {{time}}, {{snowflake_id}}
   * REQ-016: Ensure same ID value for multiple {{snowflake_id}} instances
   *
   * @param templateContent - The template content to process
   * @param file - The markdown file being created
   * @returns Processed content with variables replaced
   */
  processTemplate(templateContent, file) {
    const hasSnowflakeId = templateContent.includes("{{snowflake_id}}");
    const context = this.buildContext(file, hasSnowflakeId);
    const processedContent = this.replaceVariables(templateContent, context);
    return {
      content: processedContent,
      hasSnowflakeId,
      variables: context
    };
  }
  /**
   * Build the variable context for a file
   *
   * REQ-012: Use default date format "YYYY-MM-DD"
   * REQ-013: Use default time format "HH:mm"
   * REQ-014: Use custom formats if configured
   * REQ-015: Generate 10-character alphanumeric ID
   *
   * @param file - The file to build context for
   * @param generateId - Whether to generate a snowflake_id
   * @returns Variable context
   */
  buildContext(file, generateId) {
    const now = (0, import_obsidian9.moment)();
    const context = {
      title: file.basename,
      // filename without .md extension
      date: now.format(this.dateFormat),
      time: now.format(this.timeFormat)
    };
    if (generateId) {
      context.snowflakeId = generateNanoID();
    }
    return context;
  }
  /**
   * Replace all variables in the content
   *
   * REQ-027: If a template contains malformed variable syntax, then the
   * plugin shall leave it unchanged in the output.
   *
   * @param content - The content to process
   * @param context - The variable context
   * @returns Content with variables replaced
   */
  replaceVariables(content, context) {
    return content.replace(VARIABLE_REGEX, (match, varName) => {
      const handlerKey = varName === "snowflake_id" ? "snowflakeId" : varName;
      if (!(handlerKey in VARIABLE_HANDLERS)) {
        return match;
      }
      const handler = VARIABLE_HANDLERS[handlerKey];
      const value = handler(context);
      return value != null ? value : match;
    });
  }
  /**
   * Update date format
   *
   * REQ-014: Support custom date formats
   *
   * @param format - New date format
   */
  setDateFormat(format) {
    this.dateFormat = format !== "" ? format : DEFAULT_DATE_FORMAT;
  }
  /**
   * Update time format
   *
   * REQ-014: Support custom time formats
   *
   * @param format - New time format
   */
  setTimeFormat(format) {
    this.timeFormat = format !== "" ? format : DEFAULT_TIME_FORMAT;
  }
  /**
   * Validate a template for malformed variables
   *
   * REQ-028: When encountering invalid template variables, the plugin
   * shall show a warning to help users fix their templates.
   *
   * @param templateContent - The template to validate
   * @returns Array of invalid variable names found
   */
  validateTemplate(templateContent) {
    const invalidVars = [];
    const matches = templateContent.matchAll(VARIABLE_REGEX);
    for (const match of matches) {
      const varName = match[1];
      if (!(varName in VARIABLE_HANDLERS) && varName !== "snowflake_id") {
        invalidVars.push(varName);
      }
    }
    return [...new Set(invalidVars)];
  }
  /**
   * Get list of available variables
   *
   * @returns Array of variable names
   */
  getAvailableVariables() {
    return Object.keys(VARIABLE_HANDLERS);
  }
};

// src/frontmatter-merger.ts
var FRONTMATTER_REGEX = /^---\s*\n([\s\S]*?)\n---\s*$/m;
var FrontmatterMerger = class {
  /**
   * Merge two frontmatter sections
   *
   * REQ-008: Intelligently merge frontmatter blocks
   * REQ-009: Incoming values take precedence (except for lists)
   * REQ-010: Add new keys from incoming frontmatter
   * REQ-010a: Concatenate list-type fields (base first, then incoming)
   *
   * @param baseFrontmatter - The base frontmatter content
   * @param incomingFrontmatter - The incoming frontmatter to merge
   * @returns Merge result with conflicts and additions tracked
   */
  mergeFrontmatter(baseFrontmatter, incomingFrontmatter) {
    const baseFm = this.parseYaml(baseFrontmatter);
    const incomingFm = this.parseYaml(incomingFrontmatter);
    const conflicts = [];
    const added = [];
    const mergedData = { ...baseFm };
    for (const [key, value] of Object.entries(incomingFm)) {
      if (key in baseFm) {
        const baseVal = baseFm[key];
        const isBaseArray = Array.isArray(baseVal);
        const isIncomingArray = Array.isArray(value);
        const isBaseEmpty = baseVal === "" || baseVal === null || baseVal === void 0;
        const isIncomingEmpty = value === "" || value === null || value === void 0;
        if ((isBaseArray || isBaseEmpty) && (isIncomingArray || isIncomingEmpty)) {
          if (isBaseEmpty && isIncomingEmpty && !isBaseArray && !isIncomingArray) {
            mergedData[key] = "";
          } else {
            const baseArray = isBaseArray ? baseVal : [];
            const incomingArray = isIncomingArray ? value : [];
            mergedData[key] = this.concatenateArrays(baseArray, incomingArray);
          }
          conflicts.push(key);
        } else {
          mergedData[key] = value;
          conflicts.push(key);
        }
      } else {
        mergedData[key] = value;
        added.push(key);
      }
    }
    const mergedYaml = this.dataToYaml(mergedData);
    return {
      merged: mergedYaml,
      conflicts,
      added
    };
  }
  /**
   * Merge template frontmatter with existing file frontmatter
   *
   * Convenience method that extracts frontmatter from file content
   *
   * @param fileContent - The existing file content (may or may not have frontmatter)
   * @param templateFrontmatter - The template's frontmatter content
   * @returns Merge result with conflicts and additions tracked
   */
  mergeWithFile(fileContent, templateFrontmatter) {
    const fileFm = this.parseFrontmatter(fileContent);
    return this.mergeFrontmatter(templateFrontmatter, fileFm.content);
  }
  /**
   * Apply merged frontmatter to file content
   *
   * @param fileContent - Original file content
   * @param mergedFrontmatter - The merged frontmatter YAML
   * @returns File content with updated frontmatter
   */
  applyToFile(fileContent, mergedFrontmatter) {
    const parsed = this.parseFrontmatter(fileContent);
    const formattedFrontmatter = `---
${mergedFrontmatter}---`;
    if (parsed.exists && parsed.endPosition !== void 0) {
      return formattedFrontmatter + fileContent.slice(parsed.endPosition);
    } else {
      return formattedFrontmatter + "\n" + fileContent;
    }
  }
  /**
   * Parse frontmatter from file content
   *
   * @param content - File content
   * @returns Parsed frontmatter information
   */
  parseFrontmatter(content) {
    const match = content.match(FRONTMATTER_REGEX);
    if (!match) {
      return {
        exists: false,
        content: "",
        data: {}
      };
    }
    const frontmatterContent = match[1];
    const matchIndex = match.index;
    if (matchIndex === void 0) {
      return {
        exists: false,
        content: "",
        data: {}
      };
    }
    const endPosition = matchIndex + match[0].length;
    return {
      exists: true,
      content: frontmatterContent,
      data: this.parseYaml(frontmatterContent),
      endPosition
    };
  }
  /**
   * Parse YAML content into a data object
   *
   * This is a simple YAML parser that handles basic key-value pairs.
   * For more complex YAML structures, consider using a full YAML library.
   *
   * @param yaml - YAML content
   * @returns Parsed data object
   */
  parseYaml(yaml) {
    const data = {};
    const lines = yaml.split("\n");
    const state = this.createParserState();
    for (const line of lines) {
      this.processYamlLine(line, data, state);
    }
    this.savePendingValue(data, state);
    return data;
  }
  createParserState() {
    return { currentKey: null, currentValue: [] };
  }
  processYamlLine(line, data, state) {
    if (!line.trim() || line.trim().startsWith("#")) {
      return;
    }
    const keyMatch = line.match(/^([^:]+?):\s*(.*)$/);
    if (keyMatch) {
      this.handleKeyValueLine(keyMatch, data, state);
    } else if (state.currentKey !== null) {
      const arrayMatch = line.match(/^\s*- (.*)$/);
      if (arrayMatch) {
        if (!Array.isArray(data[state.currentKey])) {
          data[state.currentKey] = [];
        }
        const itemContent = arrayMatch[1].trim();
        if (itemContent === "") {
          data[state.currentKey].push("");
        } else {
          const itemValue = this.parseValue(itemContent);
          data[state.currentKey].push(itemValue);
        }
      } else if (line.startsWith("  ")) {
        state.currentValue.push(line.slice(2));
      }
    }
  }
  handleKeyValueLine(keyMatch, data, state) {
    this.savePendingValue(data, state);
    state.currentKey = keyMatch[1].trim();
    const value = keyMatch[2].trim();
    if (value === "|") {
      state.currentValue = [];
    } else if (value !== "") {
      data[state.currentKey] = this.parseValue(value);
      state.currentKey = null;
      state.currentValue = [];
    } else {
      state.currentValue = [];
    }
  }
  savePendingValue(data, state) {
    if (state.currentKey !== null) {
      if (state.currentValue.length > 0) {
        data[state.currentKey] = state.currentValue.join("\n").trim();
      } else if (!(state.currentKey in data)) {
        data[state.currentKey] = "";
      }
    }
  }
  /**
   * Parse a YAML value, handling basic types
   *
   * @param value - String value to parse
   * @returns Parsed value (string, number, boolean, or array)
   */
  parseValue(value) {
    const unquoted = this.tryUnquote(value);
    if (unquoted !== value) return unquoted;
    const booleanValue = this.tryParseBoolean(value);
    if (booleanValue !== void 0) return booleanValue;
    if (value === "null" || value === "~") return null;
    const numberValue = this.tryParseNumber(value);
    if (numberValue !== void 0) return numberValue;
    const arrayValue = this.tryParseArray(value);
    if (arrayValue !== void 0) return arrayValue;
    return value;
  }
  tryUnquote(value) {
    if (value.startsWith('"') && value.endsWith('"') || value.startsWith("'") && value.endsWith("'")) {
      return value.slice(1, -1);
    }
    return value;
  }
  tryParseBoolean(value) {
    if (value === "true") return true;
    if (value === "false") return false;
    return void 0;
  }
  tryParseNumber(value) {
    if (/^-?\d+(\.\d+)?$/.test(value)) {
      return parseFloat(value);
    }
    return void 0;
  }
  tryParseArray(value) {
    if (value.startsWith("[") && value.endsWith("]")) {
      const inner = value.slice(1, -1).trim();
      if (inner === "") {
        return [];
      }
      return inner.split(",").map((item) => this.parseValue(item.trim())).filter((item) => item !== "");
    }
    return void 0;
  }
  /**
   * Convert data object to YAML format
   *
   * @param data - Data object to convert
   * @returns YAML string
   */
  dataToYaml(data) {
    const lines = [];
    for (const [key, value] of Object.entries(data)) {
      const yamlLine = this.formatYamlLine(key, value);
      if (Array.isArray(yamlLine)) {
        lines.push(...yamlLine);
      } else {
        lines.push(yamlLine);
      }
    }
    return lines.join("\n") + "\n";
  }
  formatYamlLine(key, value) {
    if (value === null || value === void 0) {
      return `${key}: null`;
    }
    if (value === "") {
      return `${key}: `;
    }
    if (typeof value === "boolean" || typeof value === "number") {
      return `${key}: ${String(value)}`;
    }
    if (Array.isArray(value)) {
      if (value.length === 0) {
        return `${key}: []`;
      }
      const lines = [`${key}:`];
      for (const item of value) {
        lines.push(`  - ${this.formatValue(item)}`);
      }
      return lines;
    }
    if (typeof value === "string") {
      return this.formatStringValue(key, value);
    }
    if (typeof value === "object") {
      return `${key}: ${JSON.stringify(value)}`;
    }
    return `${key}: ${JSON.stringify(value)}`;
  }
  formatStringValue(key, value) {
    if (!value.includes("\n")) {
      return `${key}: ${this.formatValue(value)}`;
    }
    if (value.trim() === "|") {
      return `${key}: |`;
    }
    const lines = [`${key}: |`];
    const valueLines = value.split("\n");
    for (const line of valueLines) {
      lines.push(`  ${line}`);
    }
    return lines;
  }
  /**
   * Format a value for YAML output
   *
   * @param value - Value to format
   * @returns Formatted string
   */
  formatValue(value) {
    if (typeof value === "string") {
      if (value.startsWith('"') && value.endsWith('"') || value.startsWith("'") && value.endsWith("'")) {
        return value;
      }
      if (/[:[\]{},>|]/.test(value)) {
        return `"${value.replace(/"/g, '\\"')}"`;
      }
      return value;
    }
    return String(value);
  }
  /**
   * Concatenate two arrays with deduplication
   *
   * REQ-010a: When merging list-type fields, concatenate values
   * Preserves order: base array items first, then incoming items
   * Removes duplicates based on first occurrence
   *
   * @param baseArray - The base array
   * @param incomingArray - The array to concatenate
   * @returns Concatenated array with duplicates removed
   */
  concatenateArrays(baseArray, incomingArray) {
    const result = [];
    const seen = /* @__PURE__ */ new Set();
    const addUniqueItem = (item) => {
      const key = JSON.stringify(item);
      if (!seen.has(key)) {
        seen.add(key);
        result.push(item);
      }
    };
    for (const item of baseArray) {
      addUniqueItem(item);
    }
    for (const item of incomingArray) {
      addUniqueItem(item);
    }
    return result;
  }
  /**
   * Validate frontmatter syntax
   *
   * @param yaml - YAML content to validate
   * @returns True if valid, false otherwise
   */
  validateYaml(yaml) {
    try {
      const parsed = this.parseYaml(yaml);
      return typeof parsed === "object";
    } catch (e) {
      return false;
    }
  }
  /**
   * Extract delete list from frontmatter content
   *
   * REQ-034: Templates can have delete: [prop1, prop2] to exclude properties
   * REQ-037: The delete property defines exclusions for inheritance
   *
   * @param frontmatterContent - The frontmatter YAML content
   * @returns Array of property names to exclude, or null if no delete list
   */
  extractDeleteList(frontmatterContent) {
    const data = this.parseYaml(frontmatterContent);
    const deleteValue = data["delete"];
    if (deleteValue === void 0) {
      return null;
    }
    if (!Array.isArray(deleteValue)) {
      return null;
    }
    const validProperties = deleteValue.filter(
      (item) => typeof item === "string" && item.trim() !== ""
    );
    return validProperties.length > 0 ? validProperties : null;
  }
  /**
   * Apply delete list exclusions to frontmatter
   *
   * REQ-034: Remove properties listed in delete list
   * REQ-036: Always remove the "delete" property itself
   * REQ-037: Don't remove properties that are explicitly defined
   *
   * @param frontmatterContent - The frontmatter YAML content
   * @param deleteList - Array of property names to exclude
   * @param explicitlyDefined - Optional set of properties defined in current template
   * @returns Frontmatter with exclusions applied
   */
  applyDeleteList(frontmatterContent, deleteList, explicitlyDefined) {
    const data = this.parseYaml(frontmatterContent);
    const processedData = {};
    for (const [key, value] of Object.entries(data)) {
      if (key === "delete") {
        continue;
      }
      if (explicitlyDefined && explicitlyDefined.has(key)) {
        processedData[key] = value;
        continue;
      }
      if (deleteList.includes(key)) {
        continue;
      }
      processedData[key] = value;
    }
    return this.dataToYaml(processedData);
  }
  /**
   * Process frontmatter with delete list handling during template inheritance
   *
   * REQ-034: Apply delete list exclusions
   * REQ-035: Handle cumulative exclusions with override capability
   * REQ-036: Remove "delete" property from result
   * REQ-037: Explicit definitions override exclusions
   *
   * @param frontmatter - The frontmatter content to process
   * @param cumulativeDeleteList - Cumulative delete list from parent templates
   * @returns Processed result with delete list tracking
   */
  processWithDeleteList(frontmatter, cumulativeDeleteList = []) {
    const currentDeleteList = this.extractDeleteList(frontmatter) || [];
    const data = this.parseYaml(frontmatter);
    const explicitlyDefined = /* @__PURE__ */ new Set();
    for (const key of Object.keys(data)) {
      if (key !== "delete") {
        explicitlyDefined.add(key);
      }
    }
    const processedContent = this.applyDeleteList(
      frontmatter,
      cumulativeDeleteList,
      explicitlyDefined
    );
    const newDeleteList = [...cumulativeDeleteList];
    for (const prop of currentDeleteList) {
      if (!explicitlyDefined.has(prop) && !newDeleteList.includes(prop)) {
        newDeleteList.push(prop);
      }
    }
    return { processedContent, newDeleteList };
  }
  /**
   * Extract property names from frontmatter content
   *
   * @param frontmatterContent - The frontmatter YAML content
   * @returns Set of property names (excluding 'delete' property)
   */
  extractPropertyNames(frontmatterContent) {
    const data = this.parseYaml(frontmatterContent);
    const properties = /* @__PURE__ */ new Set();
    for (const key of Object.keys(data)) {
      if (key !== "delete") {
        properties.add(key);
      }
    }
    return properties;
  }
  /**
   * Check if a value is considered empty for cleanup purposes
   *
   * REQ-038: Empty values are: empty string, null, empty array
   * NOT empty: false, 0, undefined (undefined means property doesn't exist)
   *
   * @param value - The value to check
   * @returns True if the value is considered empty
   */
  isEmptyValue(value) {
    if (value === null) {
      return true;
    }
    if (typeof value === "string" && value.trim() === "") {
      return true;
    }
    if (Array.isArray(value) && value.length === 0) {
      return true;
    }
    return false;
  }
  /**
   * Clean up empty properties that don't come from templates
   *
   * REQ-038: Remove properties that are empty and not from template chain
   *
   * @param frontmatterContent - The merged frontmatter content
   * @param templateProperties - Set of properties that came from templates
   * @returns Cleaned frontmatter content
   */
  cleanupEmptyProperties(frontmatterContent, templateProperties) {
    const data = this.parseYaml(frontmatterContent);
    const cleanedData = {};
    for (const [key, value] of Object.entries(data)) {
      const isFromTemplate = templateProperties.has(key);
      const isEmpty = this.isEmptyValue(value);
      if (isFromTemplate || !isEmpty) {
        cleanedData[key] = value;
      }
    }
    const result = this.dataToYaml(cleanedData);
    return result;
  }
  /**
   * Merge template frontmatter with accumulated frontmatter considering delete lists
   *
   * This method handles the complete merge process including:
   * - Extracting and managing cumulative delete lists
   * - Tracking explicitly defined properties
   * - Applying delete lists after merging
   *
   * @param accumulatedFrontmatter - The accumulated frontmatter from parent templates
   * @param currentTemplateFrontmatter - The current template's frontmatter
   * @param cumulativeDeleteList - The cumulative delete list from parent templates
   * @returns Object containing merged frontmatter and updated delete list
   */
  mergeWithDeleteList(accumulatedFrontmatter, currentTemplateFrontmatter, cumulativeDeleteList) {
    const currentDeleteList = this.extractDeleteList(currentTemplateFrontmatter);
    const data = this.parseYaml(currentTemplateFrontmatter);
    const explicitlyDefined = new Set(Object.keys(data).filter((k) => k !== "delete"));
    const updatedDeleteList = cumulativeDeleteList.filter((prop) => !explicitlyDefined.has(prop));
    if (currentDeleteList) {
      for (const prop of currentDeleteList) {
        if (!explicitlyDefined.has(prop) && !updatedDeleteList.includes(prop)) {
          updatedDeleteList.push(prop);
        }
      }
    }
    const deleteResult = this.processWithDeleteList(
      currentTemplateFrontmatter,
      cumulativeDeleteList
    );
    const mergeResult = this.mergeFrontmatter(
      accumulatedFrontmatter,
      deleteResult.processedContent
    );
    const mergedFrontmatter = this.applyDeleteList(
      mergeResult.merged,
      updatedDeleteList,
      explicitlyDefined
    );
    return { mergedFrontmatter, updatedDeleteList };
  }
};

// src/template-applicator.ts
var TemplateApplicator = class {
  constructor(vault, settings) {
    this.vault = vault;
    this.loader = new TemplateLoader(vault, settings);
    this.variableProcessor = new TemplateVariableProcessor(
      settings.dateFormat,
      settings.timeFormat
    );
    this.frontmatterMerger = new FrontmatterMerger();
    this.errorHandler = ErrorHandler.getInstance();
  }
  /**
   * Apply a template to a file
   *
   * REQ-025: Manual commands always work
   *
   * @param file - The file to apply template to
   * @param context - Command context (manual vs automatic)
   * @param editor - Optional editor for cursor position
   * @returns Application result
   */
  async applyTemplate(file, context = { isManualCommand: false }, editor) {
    const chain = this.loader.getTemplateChain(file);
    if (chain.templates.length === 0) {
      return { success: false, message: "No template configured for this location" };
    }
    const loadedChain = await this.loader.loadTemplateChain(chain);
    if (loadedChain.templates.length === 0) {
      return { success: false, message: "No templates could be loaded" };
    }
    const finalTemplateContent = this.mergeTemplates(loadedChain.templates);
    const templateProperties = this.extractPropertiesFromFinalTemplate(finalTemplateContent);
    const result = await this.applyProcessedTemplateContent(
      file,
      finalTemplateContent,
      templateProperties,
      editor,
      context
    );
    if (result.success && context.isBatchOperation !== true) {
      const templateNames = loadedChain.templates.map((t) => t.path).join(" \u2192 ");
      console.info(`Snowflake: Template(s) "${templateNames}" applied to ${file.path}`);
    }
    return result;
  }
  /**
   * Apply a specific template to a file (for manual commands)
   *
   * @param file - The file to apply template to
   * @param templatePath - Specific template to apply
   * @param editor - Optional editor for cursor position
   * @returns Application result
   */
  async applySpecificTemplate(file, templatePath, editor) {
    try {
      const templateContent = await this.loader.loadTemplate(templatePath);
      if (templateContent === null) {
        console.error(`Snowflake: Template not found: ${templatePath}`);
        return {
          success: false,
          message: `Template not found: ${templatePath}`
        };
      }
      const cleanedTemplateContent = this.removeDeletePropertyFromTemplate(templateContent);
      const processedTemplate = this.variableProcessor.processTemplate(
        cleanedTemplateContent,
        file
      );
      const result = await this.applyProcessedTemplate(file, processedTemplate.content, editor);
      if (result.success) {
        console.info(`Snowflake: Template "${templatePath}" applied to ${file.path}`);
      }
      return {
        ...result,
        hadSnowflakeId: processedTemplate.hasSnowflakeId
      };
    } catch (error) {
      const errorContext = {
        operation: "apply_template",
        filePath: file.path,
        templatePath
      };
      const errorMessage = this.errorHandler.handleError(error, errorContext);
      return {
        success: false,
        message: errorMessage
      };
    }
  }
  /**
   * Apply processed template content to a file
   *
   * REQ-006: Merge template with existing content
   * REQ-007: Insert body at cursor position
   * REQ-039: Apply only frontmatter in batch operations
   *
   * @param file - The file to apply to
   * @param processedContent - The processed template content
   * @param editor - Optional editor for cursor position
   * @param context - Command context with batch operation flag
   * @returns Application result
   */
  async applyProcessedTemplate(file, processedContent, editor, context) {
    const currentContent = await this.vault.read(file);
    const templateParts = this.splitContent(processedContent);
    const currentParts = this.splitContent(currentContent);
    const { content: contentAfterFrontmatter, updatedBody } = this.processFrontmatter(
      currentContent,
      templateParts,
      currentParts
    );
    const isBatchOperation = (context == null ? void 0 : context.isBatchOperation) === true;
    const shouldSkipBody = isBatchOperation && updatedBody.trim() !== "";
    let finalContent;
    if (shouldSkipBody) {
      finalContent = contentAfterFrontmatter;
    } else {
      finalContent = this.processBodyContent(
        contentAfterFrontmatter,
        templateParts.body,
        updatedBody,
        editor
      );
    }
    const normalizedContent = finalContent.trimEnd() + "\n";
    await this.vault.modify(file, normalizedContent);
    return { success: true, message: "Template applied successfully" };
  }
  processFrontmatter(currentContent, templateParts, currentParts) {
    if (templateParts.frontmatter === null || templateParts.frontmatter === "") {
      return { content: currentContent, updatedBody: currentParts.body };
    }
    const mergeResult = this.frontmatterMerger.mergeWithFile(
      currentContent,
      templateParts.frontmatter
    );
    const contentWithMergedFrontmatter = this.frontmatterMerger.applyToFile(
      currentContent,
      mergeResult.merged
    );
    const newParts = this.splitContent(contentWithMergedFrontmatter);
    return { content: contentWithMergedFrontmatter, updatedBody: newParts.body };
  }
  processBodyContent(currentContent, templateBody, currentBody, editor) {
    if (templateBody === "") {
      return currentContent;
    }
    if (currentBody === "" || editor === void 0) {
      const trimmedContent = currentContent.trimEnd();
      const trimmedTemplate = templateBody.trimEnd();
      if (trimmedContent !== "") {
        return trimmedContent + "\n" + trimmedTemplate;
      }
      return trimmedTemplate;
    }
    return this.insertAtCursor(currentContent, templateBody, currentBody, editor);
  }
  insertAtCursor(currentContent, templateBody, currentBody, editor) {
    const cursor = editor.getCursor();
    const lines = currentBody.split("\n");
    const trimmedTemplateBody = templateBody.trimEnd();
    if (cursor.line < lines.length) {
      lines[cursor.line] = lines[cursor.line].slice(0, cursor.ch) + trimmedTemplateBody + lines[cursor.line].slice(cursor.ch);
    } else {
      lines.push(trimmedTemplateBody);
    }
    const parts = this.splitContent(currentContent);
    return parts.frontmatterBlock + lines.join("\n");
  }
  /**
   * Split content into frontmatter and body parts
   *
   * @param content - Content to split
   * @returns Split content parts
   */
  splitContent(content) {
    const frontmatterMatch = content.match(/^---\s*\n([\s\S]*?)\n---\s*\n?/);
    if (frontmatterMatch) {
      return {
        frontmatter: frontmatterMatch[1],
        frontmatterBlock: frontmatterMatch[0],
        body: content.slice(frontmatterMatch[0].length)
      };
    }
    return {
      frontmatter: null,
      frontmatterBlock: "",
      body: content
    };
  }
  /**
   * Apply processed template content with empty property cleanup
   *
   * REQ-038: Remove empty properties not from templates
   * REQ-039: Apply only frontmatter in batch operations
   *
   * @param file - The file to apply to
   * @param templateContent - The raw template content
   * @param templateProperties - Properties from the template chain
   * @param editor - Optional editor for cursor position
   * @param context - Command context with batch operation flag
   * @returns Application result
   */
  async applyProcessedTemplateContent(file, templateContent, templateProperties, editor, context) {
    try {
      const currentContent = await this.vault.read(file);
      const hasExistingContent = currentContent.trim() !== "";
      const processedTemplate = this.variableProcessor.processTemplate(templateContent, file);
      const result = await this.applyProcessedTemplate(
        file,
        processedTemplate.content,
        editor,
        context
      );
      if (result.success && hasExistingContent) {
        await this.cleanupEmptyProperties(file, templateProperties);
      }
      return {
        ...result,
        hadSnowflakeId: processedTemplate.hasSnowflakeId
      };
    } catch (error) {
      const errorContext = {
        operation: "apply_template",
        filePath: file.path
      };
      const errorMessage = this.errorHandler.handleError(error, errorContext);
      return {
        success: false,
        message: errorMessage
      };
    }
  }
  /**
   * Update settings reference
   *
   * @param settings - New settings
   */
  updateSettings(settings) {
    this.loader.updateSettings(settings);
    this.variableProcessor.setDateFormat(settings.dateFormat);
    this.variableProcessor.setTimeFormat(settings.timeFormat);
  }
  /**
   * Merge multiple templates into a single template
   *
   * REQ-033: Merge templates with child templates taking precedence
   * REQ-033a: Concatenate list-type fields across inheritance chain
   *
   * @param templates - Templates to merge (ordered from root to leaf)
   * @returns Merged template content
   */
  mergeTemplates(templates) {
    if (templates.length === 0) {
      return "";
    }
    const { frontmatter, body } = this.accumulateTemplateContent(templates);
    return this.formatMergedContent(frontmatter, body);
  }
  /**
   * Accumulate frontmatter and body content from templates
   *
   * REQ-034: Apply delete list exclusions from templates
   * REQ-035: Track cumulative delete list through inheritance chain
   * REQ-036: Remove "delete" property from final result
   * REQ-037: Allow explicit redefinition to override exclusions
   */
  accumulateTemplateContent(templates) {
    let accumulatedFrontmatter = "";
    let accumulatedBody = "";
    let cumulativeDeleteList = [];
    for (const template of templates) {
      if (template.content === void 0 || template.content === "") {
        continue;
      }
      const parts = this.splitContent(template.content);
      if (parts.frontmatter !== null && parts.frontmatter.trim() !== "") {
        if (accumulatedFrontmatter === "") {
          const deleteResult = this.frontmatterMerger.processWithDeleteList(
            parts.frontmatter,
            cumulativeDeleteList
          );
          accumulatedFrontmatter = deleteResult.processedContent;
          cumulativeDeleteList = deleteResult.newDeleteList;
        } else {
          const result = this.frontmatterMerger.mergeWithDeleteList(
            accumulatedFrontmatter,
            parts.frontmatter,
            cumulativeDeleteList
          );
          accumulatedFrontmatter = result.mergedFrontmatter;
          cumulativeDeleteList = result.updatedDeleteList;
        }
      }
      if (parts.body.trim() !== "") {
        if (accumulatedBody !== "") {
          accumulatedBody += "\n\n";
        }
        accumulatedBody += parts.body.trim();
      }
    }
    return { frontmatter: accumulatedFrontmatter, body: accumulatedBody };
  }
  /**
   * Format merged frontmatter and body into final content
   */
  formatMergedContent(frontmatter, body) {
    if (frontmatter !== "") {
      const trimmedFrontmatter = frontmatter.trimEnd();
      let mergedContent = `---
${trimmedFrontmatter}
---`;
      if (body !== "") {
        mergedContent += "\n" + body;
      }
      return mergedContent;
    }
    return body;
  }
  /**
   * Extract property names from the final merged template
   *
   * REQ-038: Track properties that actually exist in the final template after delete lists
   *
   * @param finalTemplateContent - The final merged template content
   * @returns Set of property names in the final template
   */
  extractPropertiesFromFinalTemplate(finalTemplateContent) {
    const parts = this.splitContent(finalTemplateContent);
    if (parts.frontmatter !== null && parts.frontmatter.trim() !== "") {
      const properties = this.frontmatterMerger.extractPropertyNames(parts.frontmatter);
      return properties;
    }
    return /* @__PURE__ */ new Set();
  }
  /**
   * Clean up empty properties not from templates
   *
   * REQ-038: Remove empty properties that weren't added by template chain
   *
   * @param file - The file to clean up
   * @param templateProperties - Properties from the template chain
   */
  async cleanupEmptyProperties(file, templateProperties) {
    const content = await this.vault.read(file);
    const parts = this.splitContent(content);
    if (parts.frontmatter !== null && parts.frontmatter.trim() !== "") {
      const cleanedFrontmatter = this.frontmatterMerger.cleanupEmptyProperties(
        parts.frontmatter,
        templateProperties
      );
      if (cleanedFrontmatter !== parts.frontmatter) {
        const cleanedContent = `---
${cleanedFrontmatter}---
${parts.body}`;
        const normalizedContent = cleanedContent.trimEnd() + "\n";
        await this.vault.modify(file, normalizedContent);
      }
    }
  }
  /**
   * Remove delete property from template content
   *
   * When applying a specific template, we don't want the delete property
   * to be added to the file's frontmatter
   *
   * @param templateContent - The template content
   * @returns Template content without delete property
   */
  removeDeletePropertyFromTemplate(templateContent) {
    const parts = this.splitContent(templateContent);
    if (parts.frontmatter === null || parts.frontmatter.trim() === "") {
      return templateContent;
    }
    const result = this.frontmatterMerger.processWithDeleteList(parts.frontmatter, []);
    if (result.processedContent.trim() === "") {
      return parts.body;
    }
    return `---
${result.processedContent}---
${parts.body}`;
  }
};

// src/file-creation-handler.ts
var FileCreationHandler = class {
  constructor(plugin, vault, settings) {
    this.processingQueue = /* @__PURE__ */ new Set();
    this.createEventRef = null;
    this.renameEventRef = null;
    this.plugin = plugin;
    this.vault = vault;
    this.settings = settings;
    this.templateApplicator = new TemplateApplicator(vault, settings);
    this.errorHandler = ErrorHandler.getInstance();
  }
  /**
   * Start listening for file creation and rename/move events
   */
  start() {
    this.createEventRef = this.vault.on("create", (file) => {
      if (file instanceof import_obsidian10.TFile) {
        this.handleFileCreation(file).catch(() => {
        });
      }
    });
    this.plugin.registerEvent(this.createEventRef);
    this.renameEventRef = this.vault.on("rename", (file, oldPath) => {
      if (file instanceof import_obsidian10.TFile) {
        this.handleFileMove(file, oldPath).catch(() => {
        });
      }
    });
    this.plugin.registerEvent(this.renameEventRef);
  }
  /**
   * Stop listening for file events
   */
  stop() {
    if (this.createEventRef !== null) {
      this.vault.offref(this.createEventRef);
      this.createEventRef = null;
    }
    if (this.renameEventRef !== null) {
      this.vault.offref(this.renameEventRef);
      this.renameEventRef = null;
    }
    this.processingQueue.clear();
  }
  /**
   * Handle file creation event
   *
   * REQ-004: Check if file is markdown before processing
   *
   * @param file - The newly created file
   */
  async handleFileCreation(file) {
    await this.processFile(file);
  }
  /**
   * Common method to process a file for template application
   *
   * @param file - The file to process
   */
  async processFile(file) {
    if (!isMarkdownFile(file)) {
      return;
    }
    if (this.processingQueue.has(file.path)) {
      return;
    }
    this.processingQueue.add(file.path);
    try {
      await this.asyncProcessFile(file);
    } finally {
      this.processingQueue.delete(file.path);
    }
  }
  async asyncProcessFile(file) {
    const stillExists = this.vault.getAbstractFileByPath(file.path);
    if (!stillExists) {
      return;
    }
    let content;
    try {
      content = await this.vault.read(file);
    } catch (e) {
      return;
    }
    if (content.trim() !== "") {
      return;
    }
    try {
      const context = { isManualCommand: false };
      await this.templateApplicator.applyTemplate(file, context);
    } catch (error) {
      const errorContext = {
        operation: "apply_template",
        filePath: file.path
      };
      this.errorHandler.handleErrorSilently(error, errorContext);
    }
  }
  /**
   * Handle file move/rename event
   *
   * @param file - The file that was moved
   * @param oldPath - The previous path of the file
   */
  async handleFileMove(file, oldPath) {
    const oldDirIndex = oldPath.lastIndexOf("/");
    const newDirIndex = file.path.lastIndexOf("/");
    const oldDir = oldDirIndex === -1 ? "" : oldPath.substring(0, oldDirIndex);
    const newDir = newDirIndex === -1 ? "" : file.path.substring(0, newDirIndex);
    if (oldDir === newDir) {
      return;
    }
    await this.processFile(file);
  }
  /**
   * Update settings reference
   *
   * @param settings - New settings
   */
  updateSettings(settings) {
    this.settings = settings;
    this.templateApplicator.updateSettings(settings);
  }
  /**
   * Check if a file is currently being processed
   *
   * @param filePath - Path to check
   * @returns True if file is in processing queue
   */
  isProcessing(filePath) {
    return this.processingQueue.has(filePath);
  }
  /**
   * Get the number of files currently being processed
   *
   * @returns Number of files in processing queue
   */
  getProcessingCount() {
    return this.processingQueue.size;
  }
};

// src/commands.ts
var import_obsidian13 = require("obsidian");

// src/ui/template-selection-modal.ts
var import_obsidian11 = require("obsidian");
var TemplateSelectionModal = class extends import_obsidian11.FuzzySuggestModal {
  constructor(app, templatesFolder, onSelect) {
    super(app);
    this.templatesFolder = templatesFolder;
    this.onSelect = onSelect;
    this.setPlaceholder("Select a template to apply...");
  }
  /**
   * Get all template files from the templates folder
   */
  getItems() {
    const templateFolder = this.app.vault.getAbstractFileByPath(this.templatesFolder);
    if (!templateFolder || !(templateFolder instanceof import_obsidian11.TFolder)) {
      new import_obsidian11.Notice(`Templates folder not found: ${this.templatesFolder}`);
      return [];
    }
    const templates = [];
    import_obsidian11.Vault.recurseChildren(templateFolder, (file) => {
      if (file instanceof import_obsidian11.TFile && file.extension === "md") {
        templates.push(file);
      }
    });
    templates.sort((a, b) => a.path.localeCompare(b.path));
    return templates;
  }
  /**
   * Get display text for a template
   */
  getItemText(template) {
    const relativePath = template.path.startsWith(this.templatesFolder + "/") ? template.path.slice(this.templatesFolder.length + 1) : template.path;
    return relativePath;
  }
  /**
   * Handle template selection
   */
  onChooseItem(template, _evt) {
    this.onSelect(template);
  }
};

// src/ui/folder-modal.ts
var import_obsidian12 = require("obsidian");
var FolderSuggestModal = class extends import_obsidian12.FuzzySuggestModal {
  constructor(app, onChoose) {
    super(app);
    this.onChoose = onChoose;
  }
  getItems() {
    const folders = [];
    const rootFolder = this.app.vault.getRoot();
    folders.push(rootFolder);
    const addFolders = (folder) => {
      for (const child of folder.children) {
        if (child instanceof import_obsidian12.TFolder) {
          folders.push(child);
          addFolders(child);
        }
      }
    };
    addFolders(rootFolder);
    return folders;
  }
  getItemText(folder) {
    return folder.path || "/";
  }
  onChooseItem(folder, _evt) {
    this.onChoose(folder);
  }
};

// src/commands.ts
var SnowflakeCommands = class {
  constructor(plugin, settings) {
    this.plugin = plugin;
    this.settings = settings;
    this.templateApplicator = new TemplateApplicator(plugin.app.vault, settings);
    this.errorHandler = ErrorHandler.getInstance();
  }
  /**
   * Register all commands with Obsidian
   */
  registerCommands() {
    this.plugin.addCommand({
      id: "apply-template-to-current-note",
      name: "Apply mapped templates",
      editorCallback: (editor, view) => {
        this.applyTemplateToCurrentNote(editor, view).catch(() => {
        });
      }
    });
    this.plugin.addCommand({
      id: "insert-date",
      name: "Insert current date",
      editorCallback: (editor) => {
        this.insertDate(editor);
      }
    });
    this.plugin.addCommand({
      id: "insert-time",
      name: "Insert current time",
      editorCallback: (editor) => {
        this.insertTime(editor);
      }
    });
    this.plugin.addCommand({
      id: "apply-specific-template",
      name: "Apply specific template",
      editorCallback: (editor, view) => {
        this.applyAnyTemplateToCurrentNote(editor, view);
      }
    });
    this.plugin.addCommand({
      id: "create-note-in-folder",
      name: "Create new note in folder",
      callback: () => {
        this.createNoteInFolder();
      }
    });
  }
  /**
   * Apply template to the currently active note
   *
   * REQ-017: Apply appropriate template to current file
   * REQ-018: Follow same merging rules as automatic application
   * REQ-025: Work even when auto-templating is disabled
   */
  async applyTemplateToCurrentNote(editor, view) {
    const file = "file" in view ? view.file : view;
    if (!file) {
      new import_obsidian13.Notice("No active file");
      return;
    }
    if (!isMarkdownFile(file)) {
      new import_obsidian13.Notice("Current file is not a markdown file");
      return;
    }
    const context = { isManualCommand: true };
    try {
      const result = await this.templateApplicator.applyTemplate(file, context, editor);
      if (!result.success) {
        new import_obsidian13.Notice(result.message);
      }
    } catch (error) {
      const errorContext = {
        operation: "apply_template",
        filePath: file.path
      };
      this.errorHandler.handleError(error, errorContext);
    }
  }
  /**
   * Process all markdown files in a folder
   *
   * REQ-020: Process ALL markdown files
   * REQ-021: Async processing for UI responsiveness
   * REQ-022: Show progress and completion
   */
  async processFolderBatch(folder, skipConfirmation = false) {
    const markdownFiles = this.getMarkdownFiles(folder);
    if (markdownFiles.length === 0) {
      if (!skipConfirmation) {
        new import_obsidian13.Notice("No markdown files found in selected folder");
      }
      return null;
    }
    if (!skipConfirmation) {
      const confirmed = await this.confirmBatchOperation(folder, markdownFiles.length);
      if (!confirmed) {
        return null;
      }
    }
    const result = await this.processFilesInBatches(markdownFiles);
    if (!skipConfirmation) {
      this.showCompletionNotice(result);
    }
    return result;
  }
  /**
   * Apply template to all notes in a folder by path
   *
   * Public method for use from settings panel
   *
   * @param folderPath - Path to the folder to process
   */
  async applyTemplateToFolderPath(folderPath, skipConfirmation = false) {
    const folder = this.plugin.app.vault.getAbstractFileByPath(folderPath);
    if (!folder || !(folder instanceof import_obsidian13.TFolder)) {
      if (!skipConfirmation) {
        new import_obsidian13.Notice(`Folder not found: ${folderPath}`);
      }
      return null;
    }
    return await this.processFolderBatch(folder, skipConfirmation);
  }
  getMarkdownFiles(folder) {
    const markdownFiles = [];
    this.collectMarkdownFiles(folder, markdownFiles);
    return markdownFiles;
  }
  async processFilesInBatches(files) {
    const batchSize = 10;
    const context = { isManualCommand: true, isBatchOperation: true };
    let successCount = 0;
    for (let i = 0; i < files.length; i += batchSize) {
      const batch = files.slice(i, i + batchSize);
      const results = await this.processBatch(batch, context);
      successCount += results.reduce((sum, val) => sum + val, 0);
      await this.sleep(10);
    }
    return {
      success: successCount,
      total: files.length
    };
  }
  async processBatch(batch, context) {
    return Promise.all(
      batch.map(
        (file) => this.templateApplicator.applyTemplate(file, context).then((result) => result.success ? 1 : 0).catch((error) => {
          const errorContext = {
            operation: "apply_template",
            filePath: file.path
          };
          this.errorHandler.handleErrorSilently(error, errorContext);
          return 0;
        })
      )
    );
  }
  showCompletionNotice(result) {
    if (result.success === result.total) {
      new import_obsidian13.Notice(`Templates applied to ${String(result.success)} notes`);
    } else {
      new import_obsidian13.Notice(`Templates applied to ${String(result.success)} of ${String(result.total)} notes`);
    }
  }
  /**
   * Show confirmation dialog for batch operation
   *
   * @param folder - The folder to process
   * @param fileCount - Number of files that will be processed
   * @returns Promise resolving to true if confirmed, false if cancelled
   */
  confirmBatchOperation(folder, fileCount) {
    return new Promise((resolve) => {
      const modal = new ConfirmationModal(
        this.plugin.app,
        `Apply templates to ${String(fileCount)} notes in "${folder.path}"?`,
        "This will apply the appropriate template to all markdown files in this folder.",
        () => {
          resolve(true);
        },
        () => {
          resolve(false);
        }
      );
      modal.open();
    });
  }
  /**
   * Recursively collect all markdown files in a folder
   *
   * @param folder - Folder to search
   * @param files - Array to collect files into
   */
  collectMarkdownFiles(folder, files) {
    for (const child of folder.children) {
      if (child instanceof import_obsidian13.TFile && isMarkdownFile(child)) {
        files.push(child);
      } else if (child instanceof import_obsidian13.TFolder) {
        this.collectMarkdownFiles(child, files);
      }
    }
  }
  /**
   * Sleep for a given number of milliseconds
   *
   * @param ms - Milliseconds to sleep
   */
  sleep(ms) {
    return new Promise((resolve) => {
      setTimeout(resolve, ms);
    });
  }
  /**
   * Update settings reference
   *
   * @param settings - New settings
   */
  updateSettings(settings) {
    this.settings = settings;
    this.templateApplicator.updateSettings(settings);
  }
  /**
   * Insert current date at cursor position
   *
   * @param editor - The editor instance
   */
  insertDate(editor) {
    const date = window.moment().format(this.settings.dateFormat);
    editor.replaceSelection(date);
  }
  /**
   * Insert current time at cursor position
   *
   * @param editor - The editor instance
   */
  insertTime(editor) {
    const time = window.moment().format(this.settings.timeFormat);
    editor.replaceSelection(time);
  }
  /**
   * Apply any template to the currently active note via template selection modal
   *
   * @param editor - The editor instance
   * @param view - The markdown view or file info
   */
  applyAnyTemplateToCurrentNote(editor, view) {
    const file = "file" in view ? view.file : view;
    if (!file) {
      new import_obsidian13.Notice("No active file");
      return;
    }
    if (!isMarkdownFile(file)) {
      new import_obsidian13.Notice("Current file is not a markdown file");
      return;
    }
    const modal = new TemplateSelectionModal(
      this.plugin.app,
      this.settings.templatesFolder,
      (templateFile) => {
        this.applySelectedTemplate(file, templateFile, editor).catch(() => {
        });
      }
    );
    modal.open();
  }
  /**
   * Apply a selected template to a file
   *
   * @param file - The file to apply template to
   * @param templateFile - The template file to apply
   * @param editor - The editor instance
   */
  async applySelectedTemplate(file, templateFile, editor) {
    try {
      const result = await this.templateApplicator.applySpecificTemplate(
        file,
        templateFile.path,
        editor
      );
      if (!result.success) {
        new import_obsidian13.Notice(result.message);
      }
    } catch (error) {
      const errorContext = {
        operation: "apply_template",
        filePath: file.path,
        templatePath: templateFile.path
      };
      this.errorHandler.handleError(error, errorContext);
    }
  }
  /**
   * Create a new note in a user-selected folder
   */
  createNoteInFolder() {
    const modal = new FolderSuggestModal(this.plugin.app, (folder) => {
      this.createNoteInFolderHandler(folder).catch(() => {
      });
    });
    modal.open();
  }
  /**
   * Handle creation of a new note in the specified folder
   *
   * @param folder - The folder to create the note in
   */
  async createNoteInFolderHandler(folder) {
    try {
      let fileName = "Untitled";
      let counter = 1;
      let filePath = folder.path ? `${folder.path}/${fileName}.md` : `${fileName}.md`;
      while (this.plugin.app.vault.getAbstractFileByPath(filePath)) {
        fileName = `Untitled ${String(counter)}`;
        filePath = folder.path ? `${folder.path}/${fileName}.md` : `${fileName}.md`;
        counter++;
      }
      const file = await this.plugin.app.vault.create(filePath, "");
      const leaf = this.plugin.app.workspace.getLeaf();
      await leaf.openFile(file);
      setTimeout(() => {
        const view = this.plugin.app.workspace.getActiveViewOfType(import_obsidian13.MarkdownView);
        if (view) {
          const titleEl = view.containerEl.querySelector(".inline-title");
          if (titleEl) {
            titleEl.focus();
            const range = document.createRange();
            range.selectNodeContents(titleEl);
            const selection = window.getSelection();
            if (selection) {
              selection.removeAllRanges();
              selection.addRange(range);
            }
          }
        }
      }, 100);
    } catch (error) {
      const errorContext = {
        operation: "apply_template",
        filePath: folder.path || "/"
      };
      this.errorHandler.handleError(error, errorContext);
    }
  }
};

// src/main.ts
var SnowflakePlugin = class extends import_obsidian14.Plugin {
  async onload() {
    await this.loadSettings();
    this.commands = new SnowflakeCommands(this, this.settings);
    this.commands.registerCommands();
    this.addSettingTab(new SnowflakeSettingTab(this.app, this, this.commands));
    this.fileCreationHandler = new FileCreationHandler(this, this.app.vault, this.settings);
    this.app.workspace.onLayoutReady(() => {
      var _a;
      (_a = this.fileCreationHandler) == null ? void 0 : _a.start();
    });
  }
  onunload() {
    if (this.fileCreationHandler !== void 0) {
      this.fileCreationHandler.stop();
    }
  }
  async loadSettings() {
    const data = await this.loadData();
    if (areSettingsValid(data)) {
      this.settings = data;
    } else {
      this.settings = migrateSettings(data);
    }
    this.validateSettings();
    await this.saveSettings();
  }
  async saveSettings() {
    this.settings = cleanSettings(this.settings);
    this.validateSettings();
    const configDir = this.manifest.dir;
    if (configDir !== void 0 && configDir !== "") {
      const configPath = `${configDir}/data.json`;
      const content = JSON.stringify(this.settings, null, 2) + "\n";
      await this.app.vault.adapter.write(configPath, content);
    } else {
      await this.saveData(this.settings);
    }
    if (this.fileCreationHandler !== void 0) {
      this.fileCreationHandler.updateSettings(this.settings);
    }
    if (this.commands !== void 0) {
      this.commands.updateSettings(this.settings);
    }
  }
  /**
   * Validates and fixes settings to ensure they're properly formed
   *
   * REQ-023: Ensures all required settings exist with valid values
   */
  validateSettings() {
    if (typeof this.settings.templateMappings !== "object" || Array.isArray(this.settings.templateMappings)) {
      this.settings.templateMappings = {};
    }
    if (typeof this.settings.templatesFolder !== "string" || this.settings.templatesFolder.trim() === "") {
      this.settings.templatesFolder = "Templates";
    }
    if (!Array.isArray(this.settings.globalExcludePatterns)) {
      this.settings.globalExcludePatterns = [];
    }
  }
};
